// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { LoadContext, SaveContext } from "./context";

/**
 * The approval mode for MCP server tools.
 *
 */
export abstract class McpServerApprovalMode {
  /**
   * The shorthand property name for this type, if any.
   */
  static readonly shorthandProperty: string | undefined = "kind";

  /**
   * The kind identifier for string approval modes
   */
  kind: string = "";

  /**
   * Initializes a new instance of McpServerApprovalMode.
   */
  constructor(init?: Partial<McpServerApprovalMode>) {
    this.kind = init?.kind ?? "";
  }

  //#region Load Methods

  /**
   * Load a McpServerApprovalMode instance from a dictionary.
   * @param data - The dictionary containing the data.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerApprovalMode instance.
   */
  static load(data: Record<string, unknown>, context?: LoadContext): McpServerApprovalMode {
    if (context) {
      data = context.processInput(data);
    }

    // Handle alternate representations
    if (typeof data === "string") {
      data = { kind: data };
    } else if (typeof data === "number") {
    } else if (typeof data === "boolean") {
    }

    // Load polymorphic McpServerApprovalMode instance
    const instance = McpServerApprovalMode.loadKind(data, context);

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }

    if (context) {
      return context.processOutput(instance) as McpServerApprovalMode;
    }
    return instance;
  }

  /**
   * Load polymorphic McpServerApprovalMode based on discriminator.
   * @param data - The dictionary containing the data.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerApprovalMode instance.
   */
  private static loadKind(
    data: Record<string, unknown>,
    context?: LoadContext
  ): McpServerApprovalMode {
    const discriminatorValue = data["kind"];
    if (discriminatorValue !== undefined && discriminatorValue !== null) {
      const discriminator = String(discriminatorValue).toLowerCase();
      switch (discriminator) {
        case "always":
          return McpServerToolAlwaysRequireApprovalMode.load(data, context);
        case "never":
          return McpServerToolNeverRequireApprovalMode.load(data, context);
        case "specify":
          return McpServerToolSpecifyApprovalMode.load(data, context);
        default:
          throw new Error(`Unknown McpServerApprovalMode discriminator value: ${discriminator}`);
      }
    }

    throw new Error("Missing McpServerApprovalMode discriminator property: 'kind'");
  }

  //#endregion

  //#region Save Methods

  /**
   * Save the McpServerApprovalMode instance to a dictionary.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The dictionary representation of this instance.
   */
  save(context?: SaveContext): Record<string, unknown> {
    const obj = context ? (context.processObject(this) as McpServerApprovalMode) : this;

    const result: Record<string, unknown> = {};

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }

    if (context) {
      return context.processDict(result);
    }

    return result;
  }

  /**
   * Convert the McpServerApprovalMode instance to a YAML string.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The YAML string representation of this instance.
   */
  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  /**
   * Convert the McpServerApprovalMode instance to a JSON string.
   * @param context - Optional context with pre/post processing callbacks.
   * @param indent - Number of spaces for indentation. Defaults to 2.
   * @returns The JSON string representation of this instance.
   */
  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  /**
   * Load a McpServerApprovalMode instance from a JSON string.
   * @param json - The JSON string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerApprovalMode instance.
   */
  static fromJson(json: string, context?: LoadContext): McpServerApprovalMode {
    const data = JSON.parse(json);

    // Handle alternate representations
    if (typeof data !== "object" || data === null || Array.isArray(data)) {
      if (typeof data === "string") {
        return McpServerApprovalMode.load({ kind: data }, context);
      } else if (typeof data === "number") {
        // Check if it's an integer or float
        if (Number.isInteger(data)) {
        } else {
        }
      } else if (typeof data === "boolean") {
      }
      // Fallback - shouldn't reach here
      return McpServerApprovalMode.load({ kind: data }, context);
    }

    return McpServerApprovalMode.load(data as Record<string, unknown>, context);
  }

  /**
   * Load a McpServerApprovalMode instance from a YAML string.
   * @param yaml - The YAML string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerApprovalMode instance.
   */
  static fromYaml(yaml: string, context?: LoadContext): McpServerApprovalMode {
    const { parse } = require("yaml");
    const data = parse(yaml);

    // Handle alternate representations
    if (typeof data !== "object" || data === null || Array.isArray(data)) {
      if (typeof data === "string") {
        return McpServerApprovalMode.load({ kind: data }, context);
      } else if (typeof data === "number") {
        // Check if it's an integer or float
        if (Number.isInteger(data)) {
        } else {
        }
      } else if (typeof data === "boolean") {
      }
      // Fallback - shouldn't reach here
      return McpServerApprovalMode.load({ kind: data }, context);
    }

    return McpServerApprovalMode.load(data as Record<string, unknown>, context);
  }

  //#endregion
}

/**
 *
 *
 */
export class McpServerToolAlwaysRequireApprovalMode extends McpServerApprovalMode {
  /**
   * The shorthand property name for this type, if any.
   */
  static readonly shorthandProperty: string | undefined = undefined;

  /**
   * The kind identifier for always approval mode
   */
  kind: string = "always";

  /**
   * Initializes a new instance of McpServerToolAlwaysRequireApprovalMode.
   */
  constructor(init?: Partial<McpServerToolAlwaysRequireApprovalMode>) {
    super(init);

    this.kind = init?.kind ?? "always";
  }

  //#region Load Methods

  /**
   * Load a McpServerToolAlwaysRequireApprovalMode instance from a dictionary.
   * @param data - The dictionary containing the data.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolAlwaysRequireApprovalMode instance.
   */
  static load(
    data: Record<string, unknown>,
    context?: LoadContext
  ): McpServerToolAlwaysRequireApprovalMode {
    if (context) {
      data = context.processInput(data);
    }

    // Create new instance
    const instance = new McpServerToolAlwaysRequireApprovalMode();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }

    if (context) {
      return context.processOutput(instance) as McpServerToolAlwaysRequireApprovalMode;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  /**
   * Save the McpServerToolAlwaysRequireApprovalMode instance to a dictionary.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The dictionary representation of this instance.
   */
  save(context?: SaveContext): Record<string, unknown> {
    const obj = context
      ? (context.processObject(this) as McpServerToolAlwaysRequireApprovalMode)
      : this;

    // Start with parent class properties
    const result = super.save(context);

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }

    return result;
  }

  /**
   * Convert the McpServerToolAlwaysRequireApprovalMode instance to a YAML string.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The YAML string representation of this instance.
   */
  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  /**
   * Convert the McpServerToolAlwaysRequireApprovalMode instance to a JSON string.
   * @param context - Optional context with pre/post processing callbacks.
   * @param indent - Number of spaces for indentation. Defaults to 2.
   * @returns The JSON string representation of this instance.
   */
  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  /**
   * Load a McpServerToolAlwaysRequireApprovalMode instance from a JSON string.
   * @param json - The JSON string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolAlwaysRequireApprovalMode instance.
   */
  static fromJson(json: string, context?: LoadContext): McpServerToolAlwaysRequireApprovalMode {
    const data = JSON.parse(json);

    return McpServerToolAlwaysRequireApprovalMode.load(data as Record<string, unknown>, context);
  }

  /**
   * Load a McpServerToolAlwaysRequireApprovalMode instance from a YAML string.
   * @param yaml - The YAML string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolAlwaysRequireApprovalMode instance.
   */
  static fromYaml(yaml: string, context?: LoadContext): McpServerToolAlwaysRequireApprovalMode {
    const { parse } = require("yaml");
    const data = parse(yaml);

    return McpServerToolAlwaysRequireApprovalMode.load(data as Record<string, unknown>, context);
  }

  //#endregion
}

/**
 *
 *
 */
export class McpServerToolNeverRequireApprovalMode extends McpServerApprovalMode {
  /**
   * The shorthand property name for this type, if any.
   */
  static readonly shorthandProperty: string | undefined = undefined;

  /**
   * The kind identifier for never approval mode
   */
  kind: string = "never";

  /**
   * Initializes a new instance of McpServerToolNeverRequireApprovalMode.
   */
  constructor(init?: Partial<McpServerToolNeverRequireApprovalMode>) {
    super(init);

    this.kind = init?.kind ?? "never";
  }

  //#region Load Methods

  /**
   * Load a McpServerToolNeverRequireApprovalMode instance from a dictionary.
   * @param data - The dictionary containing the data.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolNeverRequireApprovalMode instance.
   */
  static load(
    data: Record<string, unknown>,
    context?: LoadContext
  ): McpServerToolNeverRequireApprovalMode {
    if (context) {
      data = context.processInput(data);
    }

    // Create new instance
    const instance = new McpServerToolNeverRequireApprovalMode();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }

    if (context) {
      return context.processOutput(instance) as McpServerToolNeverRequireApprovalMode;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  /**
   * Save the McpServerToolNeverRequireApprovalMode instance to a dictionary.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The dictionary representation of this instance.
   */
  save(context?: SaveContext): Record<string, unknown> {
    const obj = context
      ? (context.processObject(this) as McpServerToolNeverRequireApprovalMode)
      : this;

    // Start with parent class properties
    const result = super.save(context);

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }

    return result;
  }

  /**
   * Convert the McpServerToolNeverRequireApprovalMode instance to a YAML string.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The YAML string representation of this instance.
   */
  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  /**
   * Convert the McpServerToolNeverRequireApprovalMode instance to a JSON string.
   * @param context - Optional context with pre/post processing callbacks.
   * @param indent - Number of spaces for indentation. Defaults to 2.
   * @returns The JSON string representation of this instance.
   */
  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  /**
   * Load a McpServerToolNeverRequireApprovalMode instance from a JSON string.
   * @param json - The JSON string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolNeverRequireApprovalMode instance.
   */
  static fromJson(json: string, context?: LoadContext): McpServerToolNeverRequireApprovalMode {
    const data = JSON.parse(json);

    return McpServerToolNeverRequireApprovalMode.load(data as Record<string, unknown>, context);
  }

  /**
   * Load a McpServerToolNeverRequireApprovalMode instance from a YAML string.
   * @param yaml - The YAML string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolNeverRequireApprovalMode instance.
   */
  static fromYaml(yaml: string, context?: LoadContext): McpServerToolNeverRequireApprovalMode {
    const { parse } = require("yaml");
    const data = parse(yaml);

    return McpServerToolNeverRequireApprovalMode.load(data as Record<string, unknown>, context);
  }

  //#endregion
}

/**
 *
 *
 */
export class McpServerToolSpecifyApprovalMode extends McpServerApprovalMode {
  /**
   * The shorthand property name for this type, if any.
   */
  static readonly shorthandProperty: string | undefined = undefined;

  /**
   * The kind identifier for specify approval mode
   */
  kind: string = "specify";

  /**
   * List of tools that always require approval
   */
  alwaysRequireApprovalTools: string[] = [];

  /**
   * List of tools that never require approval
   */
  neverRequireApprovalTools: string[] = [];

  /**
   * Initializes a new instance of McpServerToolSpecifyApprovalMode.
   */
  constructor(init?: Partial<McpServerToolSpecifyApprovalMode>) {
    super(init);

    this.kind = init?.kind ?? "specify";

    this.alwaysRequireApprovalTools = init?.alwaysRequireApprovalTools ?? [];

    this.neverRequireApprovalTools = init?.neverRequireApprovalTools ?? [];
  }

  //#region Load Methods

  /**
   * Load a McpServerToolSpecifyApprovalMode instance from a dictionary.
   * @param data - The dictionary containing the data.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolSpecifyApprovalMode instance.
   */
  static load(
    data: Record<string, unknown>,
    context?: LoadContext
  ): McpServerToolSpecifyApprovalMode {
    if (context) {
      data = context.processInput(data);
    }

    // Create new instance
    const instance = new McpServerToolSpecifyApprovalMode();

    if (data["kind"] !== undefined && data["kind"] !== null) {
      instance.kind = String(data["kind"]);
    }

    if (
      data["alwaysRequireApprovalTools"] !== undefined &&
      data["alwaysRequireApprovalTools"] !== null
    ) {
      instance.alwaysRequireApprovalTools = Array.isArray(data["alwaysRequireApprovalTools"])
        ? (data["alwaysRequireApprovalTools"] as unknown[]).map((v) => String(v))
        : [];
    }

    if (
      data["neverRequireApprovalTools"] !== undefined &&
      data["neverRequireApprovalTools"] !== null
    ) {
      instance.neverRequireApprovalTools = Array.isArray(data["neverRequireApprovalTools"])
        ? (data["neverRequireApprovalTools"] as unknown[]).map((v) => String(v))
        : [];
    }

    if (context) {
      return context.processOutput(instance) as McpServerToolSpecifyApprovalMode;
    }
    return instance;
  }

  //#endregion

  //#region Save Methods

  /**
   * Save the McpServerToolSpecifyApprovalMode instance to a dictionary.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The dictionary representation of this instance.
   */
  save(context?: SaveContext): Record<string, unknown> {
    const obj = context ? (context.processObject(this) as McpServerToolSpecifyApprovalMode) : this;

    // Start with parent class properties
    const result = super.save(context);

    if (obj.kind !== undefined && obj.kind !== null) {
      result["kind"] = obj.kind;
    }

    if (obj.alwaysRequireApprovalTools !== undefined && obj.alwaysRequireApprovalTools !== null) {
      result["alwaysRequireApprovalTools"] = obj.alwaysRequireApprovalTools;
    }

    if (obj.neverRequireApprovalTools !== undefined && obj.neverRequireApprovalTools !== null) {
      result["neverRequireApprovalTools"] = obj.neverRequireApprovalTools;
    }

    return result;
  }

  /**
   * Convert the McpServerToolSpecifyApprovalMode instance to a YAML string.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The YAML string representation of this instance.
   */
  toYaml(context?: SaveContext): string {
    context = context ?? new SaveContext();
    return context.toYaml(this.save(context));
  }

  /**
   * Convert the McpServerToolSpecifyApprovalMode instance to a JSON string.
   * @param context - Optional context with pre/post processing callbacks.
   * @param indent - Number of spaces for indentation. Defaults to 2.
   * @returns The JSON string representation of this instance.
   */
  toJson(context?: SaveContext, indent: number = 2): string {
    context = context ?? new SaveContext();
    return context.toJson(this.save(context), indent);
  }

  /**
   * Load a McpServerToolSpecifyApprovalMode instance from a JSON string.
   * @param json - The JSON string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolSpecifyApprovalMode instance.
   */
  static fromJson(json: string, context?: LoadContext): McpServerToolSpecifyApprovalMode {
    const data = JSON.parse(json);

    return McpServerToolSpecifyApprovalMode.load(data as Record<string, unknown>, context);
  }

  /**
   * Load a McpServerToolSpecifyApprovalMode instance from a YAML string.
   * @param yaml - The YAML string to parse.
   * @param context - Optional context with pre/post processing callbacks.
   * @returns The loaded McpServerToolSpecifyApprovalMode instance.
   */
  static fromYaml(yaml: string, context?: LoadContext): McpServerToolSpecifyApprovalMode {
    const { parse } = require("yaml");
    const data = parse(yaml);

    return McpServerToolSpecifyApprovalMode.load(data as Record<string, unknown>, context);
  }

  //#endregion
}
