// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { Binding } from "../src/index";

describe("Binding", () => {
  describe("JSON serialization", () => {
    it("should load from JSON - example 1", () => {
      const json = `{\n  "name": "my-tool",\n  "input": "input-variable"\n}`;
      const instance = Binding.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.name).toEqual("my-tool");

      expect(instance.input).toEqual("input-variable");
    });

    it("should round-trip JSON - example 1", () => {
      const json = `{\n  "name": "my-tool",\n  "input": "input-variable"\n}`;
      const instance = Binding.fromJson(json);
      const output = instance.toJson();
      const reloaded = Binding.fromJson(output);

      expect(reloaded.name).toEqual(instance.name);

      expect(reloaded.input).toEqual(instance.input);
    });

    it("should serialize to valid JSON - example 1", () => {
      const json = `{\n  "name": "my-tool",\n  "input": "input-variable"\n}`;
      const instance = Binding.fromJson(json);
      const output = instance.toJson();
      expect(output).toBeDefined();
      const parsed = JSON.parse(output);
      expect(typeof parsed).toBe("object");
    });
  });

  describe("YAML serialization", () => {
    it("should load from YAML - example 1", () => {
      const yaml = `name: my-tool\ninput: input-variable\n`;
      const instance = Binding.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.name).toEqual("my-tool");

      expect(instance.input).toEqual("input-variable");
    });

    it("should round-trip YAML - example 1", () => {
      const yaml = `name: my-tool\ninput: input-variable\n`;
      const instance = Binding.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = Binding.fromYaml(output);

      expect(reloaded.name).toEqual(instance.name);

      expect(reloaded.input).toEqual(instance.input);
    });

    it("should serialize to valid YAML - example 1", () => {
      const yaml = `name: my-tool\ninput: input-variable\n`;
      const instance = Binding.fromYaml(yaml);
      const output = instance.toYaml();
      expect(output).toBeDefined();
      // YAML output should be parseable back
      const reloaded = Binding.fromYaml(output);
      expect(reloaded).toBeDefined();
    });
  });

  describe("alternate representations", () => {
    it("should handle string alternate representation from JSON", () => {
      const value = "example";
      const json = JSON.stringify(value);
      const instance = Binding.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.input).toEqual("example");
    });

    it("should handle string alternate representation from YAML", () => {
      const value = "example";
      const yaml = typeof value === "string" ? `"${value}"` : String(value);
      const instance = Binding.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.input).toEqual("example");
    });
  });

  describe("load and save", () => {
    it("should load from dictionary", () => {
      const data: Record<string, unknown> = {};
      const instance = Binding.load(data);
      expect(instance).toBeDefined();
    });

    it("should save to dictionary", () => {
      const instance = new Binding();
      const data = instance.save();
      expect(data).toBeDefined();
      expect(typeof data).toBe("object");
    });
  });
});
