// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { ContainerAgent } from "../src/index";

describe("ContainerAgent", () => {
  describe("JSON serialization", () => {
    it("should load from JSON - example 1", () => {
      const json = `{\n  "kind": "hosted",\n  "protocols": [\n    {\n      "protocol": "responses",\n      "version": "v0.1.1"\n    }\n  ],\n  "environmentVariables": [\n    {\n      "name": "MY_ENV_VAR",\n      "value": "my-value"\n    }\n  ]\n}`;
      const instance = ContainerAgent.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("hosted");
    });

    it("should round-trip JSON - example 1", () => {
      const json = `{\n  "kind": "hosted",\n  "protocols": [\n    {\n      "protocol": "responses",\n      "version": "v0.1.1"\n    }\n  ],\n  "environmentVariables": [\n    {\n      "name": "MY_ENV_VAR",\n      "value": "my-value"\n    }\n  ]\n}`;
      const instance = ContainerAgent.fromJson(json);
      const output = instance.toJson();
      const reloaded = ContainerAgent.fromJson(output);

      expect(reloaded.kind).toEqual(instance.kind);
    });

    it("should serialize to valid JSON - example 1", () => {
      const json = `{\n  "kind": "hosted",\n  "protocols": [\n    {\n      "protocol": "responses",\n      "version": "v0.1.1"\n    }\n  ],\n  "environmentVariables": [\n    {\n      "name": "MY_ENV_VAR",\n      "value": "my-value"\n    }\n  ]\n}`;
      const instance = ContainerAgent.fromJson(json);
      const output = instance.toJson();
      expect(output).toBeDefined();
      const parsed = JSON.parse(output);
      expect(typeof parsed).toBe("object");
    });
  });

  describe("YAML serialization", () => {
    it("should load from YAML - example 1", () => {
      const yaml = `kind: hosted\nprotocols:\n  - protocol: responses\n    version: v0.1.1\nenvironmentVariables:\n  - name: MY_ENV_VAR\n    value: my-value\n`;
      const instance = ContainerAgent.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("hosted");
    });

    it("should round-trip YAML - example 1", () => {
      const yaml = `kind: hosted\nprotocols:\n  - protocol: responses\n    version: v0.1.1\nenvironmentVariables:\n  - name: MY_ENV_VAR\n    value: my-value\n`;
      const instance = ContainerAgent.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = ContainerAgent.fromYaml(output);

      expect(reloaded.kind).toEqual(instance.kind);
    });

    it("should serialize to valid YAML - example 1", () => {
      const yaml = `kind: hosted\nprotocols:\n  - protocol: responses\n    version: v0.1.1\nenvironmentVariables:\n  - name: MY_ENV_VAR\n    value: my-value\n`;
      const instance = ContainerAgent.fromYaml(yaml);
      const output = instance.toYaml();
      expect(output).toBeDefined();
      // YAML output should be parseable back
      const reloaded = ContainerAgent.fromYaml(output);
      expect(reloaded).toBeDefined();
    });
  });

  describe("load and save", () => {
    it("should load from dictionary", () => {
      const data: Record<string, unknown> = {};
      const instance = ContainerAgent.load(data);
      expect(instance).toBeDefined();
    });

    it("should save to dictionary", () => {
      const instance = new ContainerAgent();
      const data = instance.save();
      expect(data).toBeDefined();
      expect(typeof data).toBe("object");
    });
  });
});
