// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { CustomTool } from "../src/index";

describe("CustomTool", () => {
  describe("JSON serialization", () => {
    it("should load from JSON - example 1", () => {
      const json = `{\n  "connection": {\n    "kind": "reference"\n  },\n  "options": {\n    "timeout": 30,\n    "retries": 3\n  }\n}`;
      const instance = CustomTool.fromJson(json);
      expect(instance).toBeDefined();
    });

    it("should round-trip JSON - example 1", () => {
      const json = `{\n  "connection": {\n    "kind": "reference"\n  },\n  "options": {\n    "timeout": 30,\n    "retries": 3\n  }\n}`;
      const instance = CustomTool.fromJson(json);
      const output = instance.toJson();
      const reloaded = CustomTool.fromJson(output);
    });

    it("should serialize to valid JSON - example 1", () => {
      const json = `{\n  "connection": {\n    "kind": "reference"\n  },\n  "options": {\n    "timeout": 30,\n    "retries": 3\n  }\n}`;
      const instance = CustomTool.fromJson(json);
      const output = instance.toJson();
      expect(output).toBeDefined();
      const parsed = JSON.parse(output);
      expect(typeof parsed).toBe("object");
    });
  });

  describe("YAML serialization", () => {
    it("should load from YAML - example 1", () => {
      const yaml = `connection:\n  kind: reference\noptions:\n  timeout: 30\n  retries: 3\n`;
      const instance = CustomTool.fromYaml(yaml);
      expect(instance).toBeDefined();
    });

    it("should round-trip YAML - example 1", () => {
      const yaml = `connection:\n  kind: reference\noptions:\n  timeout: 30\n  retries: 3\n`;
      const instance = CustomTool.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = CustomTool.fromYaml(output);
    });

    it("should serialize to valid YAML - example 1", () => {
      const yaml = `connection:\n  kind: reference\noptions:\n  timeout: 30\n  retries: 3\n`;
      const instance = CustomTool.fromYaml(yaml);
      const output = instance.toYaml();
      expect(output).toBeDefined();
      // YAML output should be parseable back
      const reloaded = CustomTool.fromYaml(output);
      expect(reloaded).toBeDefined();
    });
  });

  describe("load and save", () => {
    it("should load from dictionary", () => {
      const data: Record<string, unknown> = {};
      const instance = CustomTool.load(data);
      expect(instance).toBeDefined();
    });

    it("should save to dictionary", () => {
      const instance = new CustomTool();
      const data = instance.save();
      expect(data).toBeDefined();
      expect(typeof data).toBe("object");
    });
  });
});
