// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { describe, it, expect } from "vitest";
import { McpServerApprovalMode } from "../src/mcp-server-approval-mode";

describe("McpServerApprovalMode", () => {
  describe("construction", () => {
    it("should create a new instance with defaults", () => {
      const instance = new McpServerApprovalMode();
      expect(instance).toBeDefined();
    });

    it("should create a new instance with partial initialization", () => {
      const instance = new McpServerApprovalMode({});
      expect(instance).toBeDefined();
    });
  });

  describe("JSON serialization", () => {
    it("should load from JSON - example 1", () => {
      const json = `{\n  "kind": "never"\n}`;
      const instance = McpServerApprovalMode.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("never");
    });

    it("should round-trip JSON - example 1", () => {
      const json = `{\n  "kind": "never"\n}`;
      const instance = McpServerApprovalMode.fromJson(json);
      const output = instance.toJson();
      const reloaded = McpServerApprovalMode.fromJson(output);

      expect(reloaded.kind).toEqual(instance.kind);
    });
  });

  describe("YAML serialization", () => {
    it("should load from YAML - example 1", () => {
      const yaml = `kind: never\n`;
      const instance = McpServerApprovalMode.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("never");
    });

    it("should round-trip YAML - example 1", () => {
      const yaml = `kind: never\n`;
      const instance = McpServerApprovalMode.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = McpServerApprovalMode.fromYaml(output);

      expect(reloaded.kind).toEqual(instance.kind);
    });
  });

  describe("alternate representations", () => {
    it("should handle kind alternate representation", () => {
      const value = "never";
      const json = JSON.stringify(value);
      const instance = McpServerApprovalMode.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("never");
    });
  });
});
