// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { PromptAgent } from "../src/index";

describe("PromptAgent", () => {
  describe("construction", () => {
    it("should create a new instance with defaults", () => {
      const instance = new PromptAgent();
      expect(instance).toBeDefined();
    });

    it("should create a new instance with partial initialization", () => {
      const instance = new PromptAgent({});
      expect(instance).toBeDefined();
    });
  });

  describe("JSON serialization", () => {
    it("should load from JSON - example 1", () => {
      const json = `{\n  "kind": "prompt",\n  "model": {\n    "id": "gpt-35-turbo",\n    "connection": {\n      "kind": "key",\n      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",\n      "key": "{your-api-key}"\n    }\n  },\n  "tools": [\n    {\n      "name": "getCurrentWeather",\n      "kind": "function",\n      "description": "Get the current weather in a given location",\n      "parameters": {\n        "location": {\n          "kind": "string",\n          "description": "The city and state, e.g. San Francisco, CA"\n        },\n        "unit": {\n          "kind": "string",\n          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"\n        }\n      }\n    }\n  ],\n  "template": {\n    "format": "mustache",\n    "parser": "prompty"\n  },\n  "instructions": "system:\\nYou are an AI assistant who helps people find information.\\nAs the assistant, you answer questions briefly, succinctly,\\nand in a personable manner using markdown and even add some \\npersonal flair with appropriate emojis.\\n\\n# Customer\\nYou are helping {{firstName}} {{lastName}} to find answers to \\ntheir questions. Use their name to address them in your responses.\\nuser:\\n{{question}}"\n}`;
      const instance = PromptAgent.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("prompt");

      expect(instance.instructions).toEqual(
        "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
      );
    });

    it("should round-trip JSON - example 1", () => {
      const json = `{\n  "kind": "prompt",\n  "model": {\n    "id": "gpt-35-turbo",\n    "connection": {\n      "kind": "key",\n      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",\n      "key": "{your-api-key}"\n    }\n  },\n  "tools": [\n    {\n      "name": "getCurrentWeather",\n      "kind": "function",\n      "description": "Get the current weather in a given location",\n      "parameters": {\n        "location": {\n          "kind": "string",\n          "description": "The city and state, e.g. San Francisco, CA"\n        },\n        "unit": {\n          "kind": "string",\n          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"\n        }\n      }\n    }\n  ],\n  "template": {\n    "format": "mustache",\n    "parser": "prompty"\n  },\n  "instructions": "system:\\nYou are an AI assistant who helps people find information.\\nAs the assistant, you answer questions briefly, succinctly,\\nand in a personable manner using markdown and even add some \\npersonal flair with appropriate emojis.\\n\\n# Customer\\nYou are helping {{firstName}} {{lastName}} to find answers to \\ntheir questions. Use their name to address them in your responses.\\nuser:\\n{{question}}"\n}`;
      const instance = PromptAgent.fromJson(json);
      const output = instance.toJson();
      const reloaded = PromptAgent.fromJson(output);

      expect(reloaded.kind).toEqual(instance.kind);

      expect(reloaded.instructions).toEqual(instance.instructions);
    });

    it("should load from JSON - example 2", () => {
      const json = `{\n  "kind": "prompt",\n  "model": {\n    "id": "gpt-35-turbo",\n    "connection": {\n      "kind": "key",\n      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",\n      "key": "{your-api-key}"\n    }\n  },\n  "tools": {\n    "getCurrentWeather": {\n      "kind": "function",\n      "description": "Get the current weather in a given location",\n      "parameters": {\n        "location": {\n          "kind": "string",\n          "description": "The city and state, e.g. San Francisco, CA"\n        },\n        "unit": {\n          "kind": "string",\n          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"\n        }\n      }\n    }\n  },\n  "template": {\n    "format": "mustache",\n    "parser": "prompty"\n  },\n  "instructions": "system:\\nYou are an AI assistant who helps people find information.\\nAs the assistant, you answer questions briefly, succinctly,\\nand in a personable manner using markdown and even add some \\npersonal flair with appropriate emojis.\\n\\n# Customer\\nYou are helping {{firstName}} {{lastName}} to find answers to \\ntheir questions. Use their name to address them in your responses.\\nuser:\\n{{question}}"\n}`;
      const instance = PromptAgent.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("prompt");

      expect(instance.instructions).toEqual(
        "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
      );
    });

    it("should round-trip JSON - example 2", () => {
      const json = `{\n  "kind": "prompt",\n  "model": {\n    "id": "gpt-35-turbo",\n    "connection": {\n      "kind": "key",\n      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",\n      "key": "{your-api-key}"\n    }\n  },\n  "tools": {\n    "getCurrentWeather": {\n      "kind": "function",\n      "description": "Get the current weather in a given location",\n      "parameters": {\n        "location": {\n          "kind": "string",\n          "description": "The city and state, e.g. San Francisco, CA"\n        },\n        "unit": {\n          "kind": "string",\n          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"\n        }\n      }\n    }\n  },\n  "template": {\n    "format": "mustache",\n    "parser": "prompty"\n  },\n  "instructions": "system:\\nYou are an AI assistant who helps people find information.\\nAs the assistant, you answer questions briefly, succinctly,\\nand in a personable manner using markdown and even add some \\npersonal flair with appropriate emojis.\\n\\n# Customer\\nYou are helping {{firstName}} {{lastName}} to find answers to \\ntheir questions. Use their name to address them in your responses.\\nuser:\\n{{question}}"\n}`;
      const instance = PromptAgent.fromJson(json);
      const output = instance.toJson();
      const reloaded = PromptAgent.fromJson(output);

      expect(reloaded.kind).toEqual(instance.kind);

      expect(reloaded.instructions).toEqual(instance.instructions);
    });
  });

  describe("YAML serialization", () => {
    it("should load from YAML - example 1", () => {
      const yaml = `kind: prompt\nmodel:\n  id: gpt-35-turbo\n  connection:\n    kind: key\n    endpoint: https://{your-custom-endpoint}.openai.azure.com/\n    key: "{your-api-key}"\ntools:\n  - name: getCurrentWeather\n    kind: function\n    description: Get the current weather in a given location\n    parameters:\n      location:\n        kind: string\n        description: The city and state, e.g. San Francisco, CA\n      unit:\n        kind: string\n        description: The unit of temperature, e.g. Celsius or Fahrenheit\ntemplate:\n  format: mustache\n  parser: prompty\ninstructions: |-\n  system:\n  You are an AI assistant who helps people find information.\n  As the assistant, you answer questions briefly, succinctly,\n  and in a personable manner using markdown and even add some \n  personal flair with appropriate emojis.\n\n  # Customer\n  You are helping {{firstName}} {{lastName}} to find answers to \n  their questions. Use their name to address them in your responses.\n  user:\n  {{question}}\n`;
      const instance = PromptAgent.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("prompt");

      expect(instance.instructions).toEqual(
        "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
      );
    });

    it("should round-trip YAML - example 1", () => {
      const yaml = `kind: prompt\nmodel:\n  id: gpt-35-turbo\n  connection:\n    kind: key\n    endpoint: https://{your-custom-endpoint}.openai.azure.com/\n    key: "{your-api-key}"\ntools:\n  - name: getCurrentWeather\n    kind: function\n    description: Get the current weather in a given location\n    parameters:\n      location:\n        kind: string\n        description: The city and state, e.g. San Francisco, CA\n      unit:\n        kind: string\n        description: The unit of temperature, e.g. Celsius or Fahrenheit\ntemplate:\n  format: mustache\n  parser: prompty\ninstructions: |-\n  system:\n  You are an AI assistant who helps people find information.\n  As the assistant, you answer questions briefly, succinctly,\n  and in a personable manner using markdown and even add some \n  personal flair with appropriate emojis.\n\n  # Customer\n  You are helping {{firstName}} {{lastName}} to find answers to \n  their questions. Use their name to address them in your responses.\n  user:\n  {{question}}\n`;
      const instance = PromptAgent.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = PromptAgent.fromYaml(output);

      expect(reloaded.kind).toEqual(instance.kind);

      expect(reloaded.instructions).toEqual(instance.instructions);
    });

    it("should load from YAML - example 2", () => {
      const yaml = `kind: prompt\nmodel:\n  id: gpt-35-turbo\n  connection:\n    kind: key\n    endpoint: https://{your-custom-endpoint}.openai.azure.com/\n    key: "{your-api-key}"\ntools:\n  getCurrentWeather:\n    kind: function\n    description: Get the current weather in a given location\n    parameters:\n      location:\n        kind: string\n        description: The city and state, e.g. San Francisco, CA\n      unit:\n        kind: string\n        description: The unit of temperature, e.g. Celsius or Fahrenheit\ntemplate:\n  format: mustache\n  parser: prompty\ninstructions: |-\n  system:\n  You are an AI assistant who helps people find information.\n  As the assistant, you answer questions briefly, succinctly,\n  and in a personable manner using markdown and even add some \n  personal flair with appropriate emojis.\n\n  # Customer\n  You are helping {{firstName}} {{lastName}} to find answers to \n  their questions. Use their name to address them in your responses.\n  user:\n  {{question}}\n`;
      const instance = PromptAgent.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("prompt");

      expect(instance.instructions).toEqual(
        "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
      );
    });

    it("should round-trip YAML - example 2", () => {
      const yaml = `kind: prompt\nmodel:\n  id: gpt-35-turbo\n  connection:\n    kind: key\n    endpoint: https://{your-custom-endpoint}.openai.azure.com/\n    key: "{your-api-key}"\ntools:\n  getCurrentWeather:\n    kind: function\n    description: Get the current weather in a given location\n    parameters:\n      location:\n        kind: string\n        description: The city and state, e.g. San Francisco, CA\n      unit:\n        kind: string\n        description: The unit of temperature, e.g. Celsius or Fahrenheit\ntemplate:\n  format: mustache\n  parser: prompty\ninstructions: |-\n  system:\n  You are an AI assistant who helps people find information.\n  As the assistant, you answer questions briefly, succinctly,\n  and in a personable manner using markdown and even add some \n  personal flair with appropriate emojis.\n\n  # Customer\n  You are helping {{firstName}} {{lastName}} to find answers to \n  their questions. Use their name to address them in your responses.\n  user:\n  {{question}}\n`;
      const instance = PromptAgent.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = PromptAgent.fromYaml(output);

      expect(reloaded.kind).toEqual(instance.kind);

      expect(reloaded.instructions).toEqual(instance.instructions);
    });
  });

  describe("load and save", () => {
    it("should load from dictionary", () => {
      const data: Record<string, unknown> = {};
      const instance = PromptAgent.load(data);
      expect(instance).toBeDefined();
    });

    it("should save to dictionary", () => {
      const instance = new PromptAgent();
      const data = instance.save();
      expect(data).toBeDefined();
      expect(typeof data).toBe("object");
    });
  });
});
