// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import { Property } from "../src/index";

describe("Property", () => {
  describe("JSON serialization", () => {
    it("should load from JSON - example 1", () => {
      const json = `{\n  "name": "my-input",\n  "kind": "string",\n  "description": "A description of the input property",\n  "required": true,\n  "default": "default value",\n  "example": "example value",\n  "enumValues": [\n    "value1",\n    "value2",\n    "value3"\n  ]\n}`;
      const instance = Property.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.name).toEqual("my-input");

      expect(instance.kind).toEqual("string");

      expect(instance.description).toEqual("A description of the input property");

      expect(instance.required).toEqual(true);

      expect(instance.default).toEqual("default value");

      expect(instance.example).toEqual("example value");
    });

    it("should round-trip JSON - example 1", () => {
      const json = `{\n  "name": "my-input",\n  "kind": "string",\n  "description": "A description of the input property",\n  "required": true,\n  "default": "default value",\n  "example": "example value",\n  "enumValues": [\n    "value1",\n    "value2",\n    "value3"\n  ]\n}`;
      const instance = Property.fromJson(json);
      const output = instance.toJson();
      const reloaded = Property.fromJson(output);

      expect(reloaded.name).toEqual(instance.name);

      expect(reloaded.kind).toEqual(instance.kind);

      expect(reloaded.description).toEqual(instance.description);

      expect(reloaded.required).toEqual(instance.required);

      expect(reloaded.default).toEqual(instance.default);

      expect(reloaded.example).toEqual(instance.example);
    });

    it("should serialize to valid JSON - example 1", () => {
      const json = `{\n  "name": "my-input",\n  "kind": "string",\n  "description": "A description of the input property",\n  "required": true,\n  "default": "default value",\n  "example": "example value",\n  "enumValues": [\n    "value1",\n    "value2",\n    "value3"\n  ]\n}`;
      const instance = Property.fromJson(json);
      const output = instance.toJson();
      expect(output).toBeDefined();
      const parsed = JSON.parse(output);
      expect(typeof parsed).toBe("object");
    });
  });

  describe("YAML serialization", () => {
    it("should load from YAML - example 1", () => {
      const yaml = `name: my-input\nkind: string\ndescription: A description of the input property\nrequired: true\ndefault: default value\nexample: example value\nenumValues:\n  - value1\n  - value2\n  - value3\n`;
      const instance = Property.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.name).toEqual("my-input");

      expect(instance.kind).toEqual("string");

      expect(instance.description).toEqual("A description of the input property");

      expect(instance.required).toEqual(true);

      expect(instance.default).toEqual("default value");

      expect(instance.example).toEqual("example value");
    });

    it("should round-trip YAML - example 1", () => {
      const yaml = `name: my-input\nkind: string\ndescription: A description of the input property\nrequired: true\ndefault: default value\nexample: example value\nenumValues:\n  - value1\n  - value2\n  - value3\n`;
      const instance = Property.fromYaml(yaml);
      const output = instance.toYaml();
      const reloaded = Property.fromYaml(output);

      expect(reloaded.name).toEqual(instance.name);

      expect(reloaded.kind).toEqual(instance.kind);

      expect(reloaded.description).toEqual(instance.description);

      expect(reloaded.required).toEqual(instance.required);

      expect(reloaded.default).toEqual(instance.default);

      expect(reloaded.example).toEqual(instance.example);
    });

    it("should serialize to valid YAML - example 1", () => {
      const yaml = `name: my-input\nkind: string\ndescription: A description of the input property\nrequired: true\ndefault: default value\nexample: example value\nenumValues:\n  - value1\n  - value2\n  - value3\n`;
      const instance = Property.fromYaml(yaml);
      const output = instance.toYaml();
      expect(output).toBeDefined();
      // YAML output should be parseable back
      const reloaded = Property.fromYaml(output);
      expect(reloaded).toBeDefined();
    });
  });

  describe("alternate representations", () => {
    it("should handle input alternate representation from JSON", () => {
      const value = false;
      const json = JSON.stringify(value);
      const instance = Property.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("boolean");

      expect(instance.example).toEqual(false);
    });

    it("should handle input alternate representation from YAML", () => {
      const value = false;
      const yaml = typeof value === "string" ? `"${value}"` : String(value);
      const instance = Property.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("boolean");

      expect(instance.example).toEqual(false);
    });

    it("should handle input alternate representation from JSON", () => {
      const value = 3.14;
      const json = JSON.stringify(value);
      const instance = Property.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("float");

      expect(instance.example).toEqual(3.14);
    });

    it("should handle input alternate representation from YAML", () => {
      const value = 3.14;
      const yaml = typeof value === "string" ? `"${value}"` : String(value);
      const instance = Property.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("float");

      expect(instance.example).toEqual(3.14);
    });

    it("should handle input alternate representation from JSON", () => {
      const value = 4;
      const json = JSON.stringify(value);
      const instance = Property.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("integer");

      expect(instance.example).toEqual(4);
    });

    it("should handle input alternate representation from YAML", () => {
      const value = 4;
      const yaml = typeof value === "string" ? `"${value}"` : String(value);
      const instance = Property.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("integer");

      expect(instance.example).toEqual(4);
    });

    it("should handle input alternate representation from JSON", () => {
      const value = "example";
      const json = JSON.stringify(value);
      const instance = Property.fromJson(json);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("string");

      expect(instance.example).toEqual("example");
    });

    it("should handle input alternate representation from YAML", () => {
      const value = "example";
      const yaml = typeof value === "string" ? `"${value}"` : String(value);
      const instance = Property.fromYaml(yaml);
      expect(instance).toBeDefined();

      expect(instance.kind).toEqual("string");

      expect(instance.example).toEqual("example");
    });
  });

  describe("load and save", () => {
    it("should save to dictionary", () => {
      const instance = new Property();
      const data = instance.save();
      expect(data).toBeDefined();
      expect(typeof data).toBe("object");
    });
  });
});
