##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import Any, Optional

from ._context import LoadContext



@dataclass
class EnvironmentVariable:
    """Definition for an environment variable used in containerized agents.
    
    Attributes
    ----------
    name : str
        Name of the environment variable
    value : str
        Environment variable resolution
    """

    name: str = field(default="")
    value: str = field(default="")

    @staticmethod
    def load(data: Any, context: Optional[LoadContext] = None) -> "EnvironmentVariable":
        """Load a EnvironmentVariable instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            EnvironmentVariable: The loaded EnvironmentVariable instance.

        """
        
        if context is not None:
            data = context.process_input(data)
        
        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for EnvironmentVariable: {data}")

        # create new instance
        instance = EnvironmentVariable()

        if data is not None and "name" in data:
            instance.name = data["name"]
        if data is not None and "value" in data:
            instance.value = data["value"]
        if context is not None:
            instance = context.process_output(instance)
        return instance



