##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import Any, Optional

from ._context import LoadContext



@dataclass
class Parser:
    """Template parser definition
    
    Attributes
    ----------
    kind : str
        Parser used to process the rendered template into API-compatible format
    options : Optional[dict[str, Any]]
        Options for the parser
    """

    kind: str = field(default="*")
    options: Optional[dict[str, Any]] = None

    @staticmethod
    def load(data: Any, context: Optional[LoadContext] = None) -> "Parser":
        """Load a Parser instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            Parser: The loaded Parser instance.

        """
        
        if context is not None:
            data = context.process_input(data)
        
        # handle alternate representations
        if isinstance(data, str):
            data = {"kind": data}
        
        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for Parser: {data}")

        # create new instance
        instance = Parser()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "options" in data:
            instance.options = data["options"]
        if context is not None:
            instance = context.process_output(instance)
        return instance



