##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import Any, Optional

from ._context import LoadContext



@dataclass
class ProtocolVersionRecord:
    """
    
    Attributes
    ----------
    protocol : str
        The protocol type.
    version : str
        The version string for the protocol, e.g. 'v0.1.1'.
    """

    protocol: str = field(default="")
    version: str = field(default="")

    @staticmethod
    def load(data: Any, context: Optional[LoadContext] = None) -> "ProtocolVersionRecord":
        """Load a ProtocolVersionRecord instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            ProtocolVersionRecord: The loaded ProtocolVersionRecord instance.

        """
        
        if context is not None:
            data = context.process_input(data)
        
        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ProtocolVersionRecord: {data}")

        # create new instance
        instance = ProtocolVersionRecord()

        if data is not None and "protocol" in data:
            instance.protocol = data["protocol"]
        if data is not None and "version" in data:
            instance.version = data["version"]
        if context is not None:
            instance = context.process_output(instance)
        return instance



