// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestAgentDefinitionLoadJSON tests loading AgentDefinition from JSON
func TestAgentDefinitionLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionLoadYAML tests loading AgentDefinition from YAML
func TestAgentDefinitionLoadYAML(t *testing.T) {
	yamlData := `
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    answer:
      kind: string
      description: The answer to the user's question.

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionRoundtrip tests load -> save -> load produces equivalent data
func TestAgentDefinitionRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionRoundtripYAML tests YAML load -> save -> load produces equivalent data
func TestAgentDefinitionRoundtripYAML(t *testing.T) {
	yamlData := `
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    answer:
      kind: string
      description: The answer to the user's question.

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: YAML Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionToJSON tests that ToJSON produces valid JSON
func TestAgentDefinitionToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic ToJSON requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToJSON test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionToYAML tests that ToYAML produces valid YAML
func TestAgentDefinitionToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic ToYAML requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToYAML test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionLoadJSON1 tests loading AgentDefinition from JSON
func TestAgentDefinitionLoadJSON1(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionLoadYAML1 tests loading AgentDefinition from YAML
func TestAgentDefinitionLoadYAML1(t *testing.T) {
	yamlData := `
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    - name: answer
      kind: string
      description: The answer to the user's question.

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionRoundtrip1 tests load -> save -> load produces equivalent data
func TestAgentDefinitionRoundtrip1(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionRoundtripYAML1 tests YAML load -> save -> load produces equivalent data
func TestAgentDefinitionRoundtripYAML1(t *testing.T) {
	yamlData := `
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    - name: answer
      kind: string
      description: The answer to the user's question.

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: YAML Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionToJSON1 tests that ToJSON produces valid JSON
func TestAgentDefinitionToJSON1(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic ToJSON requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToJSON test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionToYAML1 tests that ToYAML produces valid YAML
func TestAgentDefinitionToYAML1(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic ToYAML requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToYAML test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionLoadJSON2 tests loading AgentDefinition from JSON
func TestAgentDefinitionLoadJSON2(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionLoadYAML2 tests loading AgentDefinition from YAML
func TestAgentDefinitionLoadYAML2(t *testing.T) {
	yamlData := `
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    answer:
      kind: string
      description: The answer to the user's question.

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionRoundtrip2 tests load -> save -> load produces equivalent data
func TestAgentDefinitionRoundtrip2(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionRoundtripYAML2 tests YAML load -> save -> load produces equivalent data
func TestAgentDefinitionRoundtripYAML2(t *testing.T) {
	yamlData := `
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    answer:
      kind: string
      description: The answer to the user's question.

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: YAML Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionToJSON2 tests that ToJSON produces valid JSON
func TestAgentDefinitionToJSON2(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic ToJSON requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToJSON test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionToYAML2 tests that ToYAML produces valid YAML
func TestAgentDefinitionToYAML2(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic ToYAML requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToYAML test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionLoadJSON3 tests loading AgentDefinition from JSON
func TestAgentDefinitionLoadJSON3(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionLoadYAML3 tests loading AgentDefinition from YAML
func TestAgentDefinitionLoadYAML3(t *testing.T) {
	yamlData := `
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    - name: answer
      kind: string
      description: The answer to the user's question.

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionRoundtrip3 tests load -> save -> load produces equivalent data
func TestAgentDefinitionRoundtrip3(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionRoundtripYAML3 tests YAML load -> save -> load produces equivalent data
func TestAgentDefinitionRoundtripYAML3(t *testing.T) {
	yamlData := `
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    - name: answer
      kind: string
      description: The answer to the user's question.

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: YAML Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionToJSON3 tests that ToJSON produces valid JSON
func TestAgentDefinitionToJSON3(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic ToJSON requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToJSON test skipped for polymorphic base types - test child types directly
}

// TestAgentDefinitionToYAML3 tests that ToYAML produces valid YAML
func TestAgentDefinitionToYAML3(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadAgentDefinition(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load AgentDefinition: %v", err)
	}
	// Polymorphic ToYAML requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToYAML test skipped for polymorphic base types - test child types directly
}
