// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestArrayPropertyLoadJSON tests loading ArrayProperty from JSON
func TestArrayPropertyLoadJSON(t *testing.T) {
	jsonData := `
{
  "items": {
    "kind": "string"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadArrayProperty(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ArrayProperty: %v", err)
	}
	_ = instance // No scalar properties to validate
}

// TestArrayPropertyLoadYAML tests loading ArrayProperty from YAML
func TestArrayPropertyLoadYAML(t *testing.T) {
	yamlData := `
items:
  kind: string

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadArrayProperty(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ArrayProperty: %v", err)
	}
	_ = instance // No scalar properties to validate
}

// TestArrayPropertyRoundtrip tests load -> save -> load produces equivalent data
func TestArrayPropertyRoundtrip(t *testing.T) {
	jsonData := `
{
  "items": {
    "kind": "string"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadArrayProperty(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ArrayProperty: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadArrayProperty(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ArrayProperty: %v", err)
	}
	_ = reloaded // No scalar properties to validate
}

// TestArrayPropertyRoundtripYAML tests YAML load -> save -> load produces equivalent data
func TestArrayPropertyRoundtripYAML(t *testing.T) {
	yamlData := `
items:
  kind: string

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadArrayProperty(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ArrayProperty: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadArrayProperty(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ArrayProperty: %v", err)
	}
	_ = reloaded // No scalar properties to validate
}

// TestArrayPropertyToJSON tests that ToJSON produces valid JSON
func TestArrayPropertyToJSON(t *testing.T) {
	jsonData := `
{
  "items": {
    "kind": "string"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadArrayProperty(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ArrayProperty: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestArrayPropertyToYAML tests that ToYAML produces valid YAML
func TestArrayPropertyToYAML(t *testing.T) {
	jsonData := `
{
  "items": {
    "kind": "string"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadArrayProperty(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ArrayProperty: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}

// TestArrayPropertyLoadFromMap tests loading ArrayProperty from an empty map
func TestArrayPropertyLoadFromMap(t *testing.T) {
	data := make(map[string]interface{})
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadArrayProperty(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ArrayProperty from map: %v", err)
	}
	_ = instance // Load succeeded
}

// TestArrayPropertySaveToMap tests saving ArrayProperty to a map
func TestArrayPropertySaveToMap(t *testing.T) {
	instance := agentschema.ArrayProperty{}
	ctx := agentschema.NewSaveContext()
	data := instance.Save(ctx)
	if data == nil {
		t.Fatal("Save returned nil")
	}
}
