// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestContainerAgentLoadJSON tests loading ContainerAgent from JSON
func TestContainerAgentLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "resources": {
    "cpu": "1",
    "memory": "2Gi"
  },
  "scale": {
    "minReplicas": 1,
    "maxReplicas": 3
  },
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ContainerAgent: %v", err)
	}
	if instance.Kind != "hosted" {
		t.Errorf(`Expected Kind to be "hosted", got %v`, instance.Kind)
	}
}

// TestContainerAgentLoadYAML tests loading ContainerAgent from YAML
func TestContainerAgentLoadYAML(t *testing.T) {
	yamlData := `
kind: hosted
protocols:
  - protocol: responses
    version: v0.1.1
resources:
  cpu: "1"
  memory: 2Gi
scale:
  minReplicas: 1
  maxReplicas: 3
environmentVariables:
  - name: MY_ENV_VAR
    value: my-value

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ContainerAgent: %v", err)
	}
	if instance.Kind != "hosted" {
		t.Errorf(`Expected Kind to be "hosted", got %v`, instance.Kind)
	}
}

// TestContainerAgentRoundtrip tests load -> save -> load produces equivalent data
func TestContainerAgentRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "resources": {
    "cpu": "1",
    "memory": "2Gi"
  },
  "scale": {
    "minReplicas": 1,
    "maxReplicas": 3
  },
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerAgent(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ContainerAgent: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadContainerAgent(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ContainerAgent: %v", err)
	}
	if reloaded.Kind != "hosted" {
		t.Errorf(`Expected Kind to be "hosted", got %v`, reloaded.Kind)
	}
}

// TestContainerAgentToJSON tests that ToJSON produces valid JSON
func TestContainerAgentToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "resources": {
    "cpu": "1",
    "memory": "2Gi"
  },
  "scale": {
    "minReplicas": 1,
    "maxReplicas": 3
  },
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ContainerAgent: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestContainerAgentToYAML tests that ToYAML produces valid YAML
func TestContainerAgentToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "resources": {
    "cpu": "1",
    "memory": "2Gi"
  },
  "scale": {
    "minReplicas": 1,
    "maxReplicas": 3
  },
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ContainerAgent: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
