// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema

import (
	"encoding/json"

	"gopkg.in/yaml.v3"
)

// ContainerScale represents Scaling configuration for a containerized agent.

type ContainerScale struct {
	MinReplicas int32 `json:"minReplicas" yaml:"minReplicas"`
	MaxReplicas int32 `json:"maxReplicas" yaml:"maxReplicas"`
}

// LoadContainerScale creates a ContainerScale from a map[string]interface{}
func LoadContainerScale(data interface{}, ctx *LoadContext) (ContainerScale, error) {
	result := ContainerScale{}

	// Load from map
	if m, ok := data.(map[string]interface{}); ok {
		if val, ok := m["minReplicas"]; ok && val != nil { // Handle various numeric types from JSON/YAML/roundtrip
			switch n := val.(type) {
			case int:
				result.MinReplicas = int32(n)
			case int32:
				result.MinReplicas = int32(n)
			case int64:
				result.MinReplicas = int32(n)
			case float64:
				result.MinReplicas = int32(n)
			}
		}
		if val, ok := m["maxReplicas"]; ok && val != nil { // Handle various numeric types from JSON/YAML/roundtrip
			switch n := val.(type) {
			case int:
				result.MaxReplicas = int32(n)
			case int32:
				result.MaxReplicas = int32(n)
			case int64:
				result.MaxReplicas = int32(n)
			case float64:
				result.MaxReplicas = int32(n)
			}
		}
	}

	return result, nil
}

// Save serializes ContainerScale to map[string]interface{}
func (obj *ContainerScale) Save(ctx *SaveContext) map[string]interface{} {
	result := make(map[string]interface{})
	result["minReplicas"] = obj.MinReplicas
	result["maxReplicas"] = obj.MaxReplicas

	return result
}

// ToJSON serializes ContainerScale to JSON string
func (obj *ContainerScale) ToJSON() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// ToYAML serializes ContainerScale to YAML string
func (obj *ContainerScale) ToYAML() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := yaml.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// FromJSON creates ContainerScale from JSON string
func ContainerScaleFromJSON(jsonStr string) (ContainerScale, error) {
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return ContainerScale{}, err
	}
	ctx := NewLoadContext()
	return LoadContainerScale(data, ctx)
}

// FromYAML creates ContainerScale from YAML string
func ContainerScaleFromYAML(yamlStr string) (ContainerScale, error) {
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlStr), &data); err != nil {
		return ContainerScale{}, err
	}
	ctx := NewLoadContext()
	return LoadContainerScale(data, ctx)
}
