// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema

import (
	"encoding/json"

	"gopkg.in/yaml.v3"
)

// ContainerResources represents Resource allocation for a containerized agent.
// Valid CPU and memory pairings depend on the target hosting provider.

type ContainerResources struct {
	Cpu    string `json:"cpu" yaml:"cpu"`
	Memory string `json:"memory" yaml:"memory"`
}

// LoadContainerResources creates a ContainerResources from a map[string]interface{}
func LoadContainerResources(data interface{}, ctx *LoadContext) (ContainerResources, error) {
	result := ContainerResources{}

	// Load from map
	if m, ok := data.(map[string]interface{}); ok {
		if val, ok := m["cpu"]; ok && val != nil {
			result.Cpu = val.(string)
		}
		if val, ok := m["memory"]; ok && val != nil {
			result.Memory = val.(string)
		}
	}

	return result, nil
}

// Save serializes ContainerResources to map[string]interface{}
func (obj *ContainerResources) Save(ctx *SaveContext) map[string]interface{} {
	result := make(map[string]interface{})
	result["cpu"] = obj.Cpu
	result["memory"] = obj.Memory

	return result
}

// ToJSON serializes ContainerResources to JSON string
func (obj *ContainerResources) ToJSON() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// ToYAML serializes ContainerResources to YAML string
func (obj *ContainerResources) ToYAML() (string, error) {
	ctx := NewSaveContext()
	data := obj.Save(ctx)
	bytes, err := yaml.Marshal(data)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

// FromJSON creates ContainerResources from JSON string
func ContainerResourcesFromJSON(jsonStr string) (ContainerResources, error) {
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return ContainerResources{}, err
	}
	ctx := NewLoadContext()
	return LoadContainerResources(data, ctx)
}

// FromYAML creates ContainerResources from YAML string
func ContainerResourcesFromYAML(yamlStr string) (ContainerResources, error) {
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlStr), &data); err != nil {
		return ContainerResources{}, err
	}
	ctx := NewLoadContext()
	return LoadContainerResources(data, ctx)
}
