// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestContainerScaleLoadJSON tests loading ContainerScale from JSON
func TestContainerScaleLoadJSON(t *testing.T) {
	jsonData := `
{
  "minReplicas": 1,
  "maxReplicas": 3
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerScale(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ContainerScale: %v", err)
	}
	if instance.MinReplicas != 1 {
		t.Errorf(`Expected MinReplicas to be 1, got %v`, instance.MinReplicas)
	}
	if instance.MaxReplicas != 3 {
		t.Errorf(`Expected MaxReplicas to be 3, got %v`, instance.MaxReplicas)
	}
}

// TestContainerScaleLoadYAML tests loading ContainerScale from YAML
func TestContainerScaleLoadYAML(t *testing.T) {
	yamlData := `
minReplicas: 1
maxReplicas: 3

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerScale(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ContainerScale: %v", err)
	}
	if instance.MinReplicas != 1 {
		t.Errorf(`Expected MinReplicas to be 1, got %v`, instance.MinReplicas)
	}
	if instance.MaxReplicas != 3 {
		t.Errorf(`Expected MaxReplicas to be 3, got %v`, instance.MaxReplicas)
	}
}

// TestContainerScaleRoundtrip tests load -> save -> load produces equivalent data
func TestContainerScaleRoundtrip(t *testing.T) {
	jsonData := `
{
  "minReplicas": 1,
  "maxReplicas": 3
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerScale(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ContainerScale: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadContainerScale(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ContainerScale: %v", err)
	}
	if reloaded.MinReplicas != 1 {
		t.Errorf(`Expected MinReplicas to be 1, got %v`, reloaded.MinReplicas)
	}
	if reloaded.MaxReplicas != 3 {
		t.Errorf(`Expected MaxReplicas to be 3, got %v`, reloaded.MaxReplicas)
	}
}

// TestContainerScaleToJSON tests that ToJSON produces valid JSON
func TestContainerScaleToJSON(t *testing.T) {
	jsonData := `
{
  "minReplicas": 1,
  "maxReplicas": 3
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerScale(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ContainerScale: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestContainerScaleToYAML tests that ToYAML produces valid YAML
func TestContainerScaleToYAML(t *testing.T) {
	jsonData := `
{
  "minReplicas": 1,
  "maxReplicas": 3
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadContainerScale(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ContainerScale: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
