// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestCustomToolLoadJSON tests loading CustomTool from JSON
func TestCustomToolLoadJSON(t *testing.T) {
	jsonData := `
{
  "connection": {
    "kind": "reference"
  },
  "options": {
    "timeout": 30,
    "retries": 3
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadCustomTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CustomTool: %v", err)
	}
	_ = instance // No scalar properties to validate
}

// TestCustomToolLoadYAML tests loading CustomTool from YAML
func TestCustomToolLoadYAML(t *testing.T) {
	yamlData := `
connection:
  kind: reference
options:
  timeout: 30
  retries: 3

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadCustomTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CustomTool: %v", err)
	}
	_ = instance // No scalar properties to validate
}

// TestCustomToolRoundtrip tests load -> save -> load produces equivalent data
func TestCustomToolRoundtrip(t *testing.T) {
	jsonData := `
{
  "connection": {
    "kind": "reference"
  },
  "options": {
    "timeout": 30,
    "retries": 3
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadCustomTool(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load CustomTool: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadCustomTool(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload CustomTool: %v", err)
	}
	_ = reloaded // No scalar properties to validate
}

// TestCustomToolRoundtripYAML tests YAML load -> save -> load produces equivalent data
func TestCustomToolRoundtripYAML(t *testing.T) {
	yamlData := `
connection:
  kind: reference
options:
  timeout: 30
  retries: 3

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadCustomTool(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load CustomTool: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadCustomTool(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload CustomTool: %v", err)
	}
	_ = reloaded // No scalar properties to validate
}

// TestCustomToolToJSON tests that ToJSON produces valid JSON
func TestCustomToolToJSON(t *testing.T) {
	jsonData := `
{
  "connection": {
    "kind": "reference"
  },
  "options": {
    "timeout": 30,
    "retries": 3
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadCustomTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CustomTool: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestCustomToolToYAML tests that ToYAML produces valid YAML
func TestCustomToolToYAML(t *testing.T) {
	jsonData := `
{
  "connection": {
    "kind": "reference"
  },
  "options": {
    "timeout": 30,
    "retries": 3
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadCustomTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CustomTool: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}

// TestCustomToolLoadFromMap tests loading CustomTool from an empty map
func TestCustomToolLoadFromMap(t *testing.T) {
	data := make(map[string]interface{})
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadCustomTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load CustomTool from map: %v", err)
	}
	_ = instance // Load succeeded
}

// TestCustomToolSaveToMap tests saving CustomTool to a map
func TestCustomToolSaveToMap(t *testing.T) {
	instance := agentschema.CustomTool{}
	ctx := agentschema.NewSaveContext()
	data := instance.Save(ctx)
	if data == nil {
		t.Fatal("Save returned nil")
	}
}
