// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestEnvironmentVariableLoadJSON tests loading EnvironmentVariable from JSON
func TestEnvironmentVariableLoadJSON(t *testing.T) {
	jsonData := `
{
  "name": "MY_ENV_VAR",
  "value": "my-value"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadEnvironmentVariable(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load EnvironmentVariable: %v", err)
	}
	if instance.Name != "MY_ENV_VAR" {
		t.Errorf(`Expected Name to be "MY_ENV_VAR", got %v`, instance.Name)
	}
	if instance.Value != "my-value" {
		t.Errorf(`Expected Value to be "my-value", got %v`, instance.Value)
	}
}

// TestEnvironmentVariableLoadYAML tests loading EnvironmentVariable from YAML
func TestEnvironmentVariableLoadYAML(t *testing.T) {
	yamlData := `
name: MY_ENV_VAR
value: my-value

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadEnvironmentVariable(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load EnvironmentVariable: %v", err)
	}
	if instance.Name != "MY_ENV_VAR" {
		t.Errorf(`Expected Name to be "MY_ENV_VAR", got %v`, instance.Name)
	}
	if instance.Value != "my-value" {
		t.Errorf(`Expected Value to be "my-value", got %v`, instance.Value)
	}
}

// TestEnvironmentVariableRoundtrip tests load -> save -> load produces equivalent data
func TestEnvironmentVariableRoundtrip(t *testing.T) {
	jsonData := `
{
  "name": "MY_ENV_VAR",
  "value": "my-value"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadEnvironmentVariable(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load EnvironmentVariable: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadEnvironmentVariable(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload EnvironmentVariable: %v", err)
	}
	if reloaded.Name != "MY_ENV_VAR" {
		t.Errorf(`Expected Name to be "MY_ENV_VAR", got %v`, reloaded.Name)
	}
	if reloaded.Value != "my-value" {
		t.Errorf(`Expected Value to be "my-value", got %v`, reloaded.Value)
	}
}

// TestEnvironmentVariableRoundtripYAML tests YAML load -> save -> load produces equivalent data
func TestEnvironmentVariableRoundtripYAML(t *testing.T) {
	yamlData := `
name: MY_ENV_VAR
value: my-value

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadEnvironmentVariable(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load EnvironmentVariable: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadEnvironmentVariable(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload EnvironmentVariable: %v", err)
	}
	if reloaded.Name != "MY_ENV_VAR" {
		t.Errorf(`Expected Name to be "MY_ENV_VAR", got %v`, reloaded.Name)
	}
	if reloaded.Value != "my-value" {
		t.Errorf(`Expected Value to be "my-value", got %v`, reloaded.Value)
	}
}

// TestEnvironmentVariableToJSON tests that ToJSON produces valid JSON
func TestEnvironmentVariableToJSON(t *testing.T) {
	jsonData := `
{
  "name": "MY_ENV_VAR",
  "value": "my-value"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadEnvironmentVariable(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load EnvironmentVariable: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestEnvironmentVariableToYAML tests that ToYAML produces valid YAML
func TestEnvironmentVariableToYAML(t *testing.T) {
	jsonData := `
{
  "name": "MY_ENV_VAR",
  "value": "my-value"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadEnvironmentVariable(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load EnvironmentVariable: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}

// TestEnvironmentVariableLoadFromMap tests loading EnvironmentVariable from an empty map
func TestEnvironmentVariableLoadFromMap(t *testing.T) {
	data := make(map[string]interface{})
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadEnvironmentVariable(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load EnvironmentVariable from map: %v", err)
	}
	_ = instance // Load succeeded
}

// TestEnvironmentVariableSaveToMap tests saving EnvironmentVariable to a map
func TestEnvironmentVariableSaveToMap(t *testing.T) {
	instance := agentschema.EnvironmentVariable{}
	ctx := agentschema.NewSaveContext()
	data := instance.Save(ctx)
	if data == nil {
		t.Fatal("Save returned nil")
	}
}
