

// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"
	
	"gopkg.in/yaml.v3"
	
	"github.com/microsoft/agentschema-go/agentschema"
)


// TestFileSearchToolLoadJSON tests loading FileSearchTool from JSON
func TestFileSearchToolLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "file_search",
  "connection": {
    "kind": "reference"
  },
  "vectorStoreIds": [
    "vectorStore1",
    "vectorStore2"
  ],
  "maximumResultCount": 10,
  "ranker": "auto",
  "scoreThreshold": 0.5,
  "filters": {
    "fileType": "pdf",
    "createdAfter": "2023-01-01"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}
	
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFileSearchTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load FileSearchTool: %v", err)
	}
	if instance.Kind != "file_search" {
		t.Errorf("Expected Kind to be "file_search", got %v", instance.Kind)
	}
	if instance.MaximumResultCount != 10 {
		t.Errorf("Expected MaximumResultCount to be 10, got %v", instance.MaximumResultCount)
	}
	if instance.Ranker != "auto" {
		t.Errorf("Expected Ranker to be "auto", got %v", instance.Ranker)
	}
	if instance.ScoreThreshold != 0.5 {
		t.Errorf("Expected ScoreThreshold to be 0.5, got %v", instance.ScoreThreshold)
	}
}

// TestFileSearchToolLoadYAML tests loading FileSearchTool from YAML
func TestFileSearchToolLoadYAML(t *testing.T) {
	yamlData := `
kind: file_search
connection:
  kind: reference
vectorStoreIds:
  - vectorStore1
  - vectorStore2
maximumResultCount: 10
ranker: auto
scoreThreshold: 0.5
filters:
  fileType: pdf
  createdAfter: 2023-01-01

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}
	
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFileSearchTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load FileSearchTool: %v", err)
	}
	if instance.Kind != "file_search" {
		t.Errorf("Expected Kind to be "file_search", got %v", instance.Kind)
	}
	if instance.MaximumResultCount != 10 {
		t.Errorf("Expected MaximumResultCount to be 10, got %v", instance.MaximumResultCount)
	}
	if instance.Ranker != "auto" {
		t.Errorf("Expected Ranker to be "auto", got %v", instance.Ranker)
	}
	if instance.ScoreThreshold != 0.5 {
		t.Errorf("Expected ScoreThreshold to be 0.5, got %v", instance.ScoreThreshold)
	}
}

// TestFileSearchToolRoundtrip tests load -> save -> load produces equivalent data
func TestFileSearchToolRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "file_search",
  "connection": {
    "kind": "reference"
  },
  "vectorStoreIds": [
    "vectorStore1",
    "vectorStore2"
  ],
  "maximumResultCount": 10,
  "ranker": "auto",
  "scoreThreshold": 0.5,
  "filters": {
    "fileType": "pdf",
    "createdAfter": "2023-01-01"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}
	
	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFileSearchTool(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load FileSearchTool: %v", err)
	}
	
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)
	
	reloaded, err := agentschema.LoadFileSearchTool(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload FileSearchTool: %v", err)
	}
	if reloaded.Kind != "file_search" {
		t.Errorf("Expected Kind to be "file_search", got %v", reloaded.Kind)
	}
	if reloaded.MaximumResultCount != 10 {
		t.Errorf("Expected MaximumResultCount to be 10, got %v", reloaded.MaximumResultCount)
	}
	if reloaded.Ranker != "auto" {
		t.Errorf("Expected Ranker to be "auto", got %v", reloaded.Ranker)
	}
	if reloaded.ScoreThreshold != 0.5 {
		t.Errorf("Expected ScoreThreshold to be 0.5, got %v", reloaded.ScoreThreshold)
	}
}

// TestFileSearchToolToJSON tests that ToJSON produces valid JSON
func TestFileSearchToolToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "file_search",
  "connection": {
    "kind": "reference"
  },
  "vectorStoreIds": [
    "vectorStore1",
    "vectorStore2"
  ],
  "maximumResultCount": 10,
  "ranker": "auto",
  "scoreThreshold": 0.5,
  "filters": {
    "fileType": "pdf",
    "createdAfter": "2023-01-01"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}
	
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFileSearchTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load FileSearchTool: %v", err)
	}
	
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}
	
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestFileSearchToolToYAML tests that ToYAML produces valid YAML
func TestFileSearchToolToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "file_search",
  "connection": {
    "kind": "reference"
  },
  "vectorStoreIds": [
    "vectorStore1",
    "vectorStore2"
  ],
  "maximumResultCount": 10,
  "ranker": "auto",
  "scoreThreshold": 0.5,
  "filters": {
    "fileType": "pdf",
    "createdAfter": "2023-01-01"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}
	
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadFileSearchTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load FileSearchTool: %v", err)
	}
	
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}
	
	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}



