

// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
"encoding/json"
"testing"

"gopkg.in/yaml.v3"

"github.com/microsoft/agentschema-go/agentschema"
)


// TestFormatLoadJSON tests loading Format from JSON
func TestFormatLoadJSON(t *testing.T) {
jsonData := `
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
`
var data map[string]interface{}
if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
t.Fatalf("Failed to parse JSON: %v", err)
}

ctx := agentschema.NewLoadContext()
instance, err := agentschema.LoadFormat(data, ctx)
if err != nil {
t.Fatalf("Failed to load Format: %v", err)
}
if instance.Kind != "mustache" {
t.Errorf("Expected Kind to be \"mustache\", got %v", instance.Kind)
}
if instance.Strict != true {
t.Errorf("Expected Strict to be true, got %v", instance.Strict)
}
}

// TestFormatLoadYAML tests loading Format from YAML
func TestFormatLoadYAML(t *testing.T) {
yamlData := `
kind: mustache
strict: true
options:
  key: value

`
var data map[string]interface{}
if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
t.Fatalf("Failed to parse YAML: %v", err)
}

ctx := agentschema.NewLoadContext()
instance, err := agentschema.LoadFormat(data, ctx)
if err != nil {
t.Fatalf("Failed to load Format: %v", err)
}
if instance.Kind != "mustache" {
t.Errorf("Expected Kind to be \"mustache\", got %v", instance.Kind)
}
if instance.Strict != true {
t.Errorf("Expected Strict to be true, got %v", instance.Strict)
}
}

// TestFormatRoundtrip tests load -> save -> load produces equivalent data
func TestFormatRoundtrip(t *testing.T) {
jsonData := `
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
`
var data map[string]interface{}
if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
t.Fatalf("Failed to parse JSON: %v", err)
}

loadCtx := agentschema.NewLoadContext()
instance, err := agentschema.LoadFormat(data, loadCtx)
if err != nil {
t.Fatalf("Failed to load Format: %v", err)
}

saveCtx := agentschema.NewSaveContext()
savedData := instance.Save(saveCtx)

reloaded, err := agentschema.LoadFormat(savedData, loadCtx)
if err != nil {
t.Fatalf("Failed to reload Format: %v", err)
}
if reloaded.Kind != "mustache" {
t.Errorf("Expected Kind to be \"mustache\", got %v", reloaded.Kind)
}
if reloaded.Strict != true {
t.Errorf("Expected Strict to be true, got %v", reloaded.Strict)
}
}

// TestFormatToJSON tests that ToJSON produces valid JSON
func TestFormatToJSON(t *testing.T) {
jsonData := `
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
`
var data map[string]interface{}
if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
t.Fatalf("Failed to parse JSON: %v", err)
}

ctx := agentschema.NewLoadContext()
instance, err := agentschema.LoadFormat(data, ctx)
if err != nil {
t.Fatalf("Failed to load Format: %v", err)
}

jsonOutput, err := instance.ToJSON()
if err != nil {
t.Fatalf("Failed to convert to JSON: %v", err)
}

var parsed map[string]interface{}
if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
t.Fatalf("Failed to parse generated JSON: %v", err)
}
}

// TestFormatToYAML tests that ToYAML produces valid YAML
func TestFormatToYAML(t *testing.T) {
jsonData := `
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
`
var data map[string]interface{}
if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
t.Fatalf("Failed to parse JSON: %v", err)
}

ctx := agentschema.NewLoadContext()
instance, err := agentschema.LoadFormat(data, ctx)
if err != nil {
t.Fatalf("Failed to load Format: %v", err)
}

yamlOutput, err := instance.ToYAML()
if err != nil {
t.Fatalf("Failed to convert to YAML: %v", err)
}

var parsed map[string]interface{}
if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
t.Fatalf("Failed to parse generated YAML: %v", err)
}
}




// TestFormatFromFormat tests loading Format from string
func TestFormatFromFormat(t *testing.T) {
ctx := agentschema.NewLoadContext()
instance, err := agentschema.LoadFormat("example", ctx)
if err != nil {
t.Fatalf("Failed to load Format from string: %v", err)
}
if instance.Kind != "example" {
t.Errorf("Expected Kind to be "example", got %v", instance.Kind)
}
}



