// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestMcpServerApprovalModeLoadJSON tests loading McpServerApprovalMode from JSON
func TestMcpServerApprovalModeLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "never"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerApprovalMode: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestMcpServerApprovalModeLoadYAML tests loading McpServerApprovalMode from YAML
func TestMcpServerApprovalModeLoadYAML(t *testing.T) {
	yamlData := `
kind: never

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerApprovalMode: %v", err)
	}
	// Polymorphic types return interface{}, extract common fields via reflection or type-specific access
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}

// TestMcpServerApprovalModeRoundtrip tests load -> save -> load produces equivalent data
func TestMcpServerApprovalModeRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "never"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerApprovalMode(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load McpServerApprovalMode: %v", err)
	}
	// Polymorphic roundtrip testing requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Roundtrip test skipped for polymorphic base types - test child types directly
}

// TestMcpServerApprovalModeToJSON tests that ToJSON produces valid JSON
func TestMcpServerApprovalModeToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "never"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerApprovalMode: %v", err)
	}
	// Polymorphic ToJSON requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToJSON test skipped for polymorphic base types - test child types directly
}

// TestMcpServerApprovalModeToYAML tests that ToYAML produces valid YAML
func TestMcpServerApprovalModeToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "never"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerApprovalMode: %v", err)
	}
	// Polymorphic ToYAML requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: ToYAML test skipped for polymorphic base types - test child types directly
}

// TestMcpServerApprovalModeFromKind tests loading McpServerApprovalMode from string
func TestMcpServerApprovalModeFromKind(t *testing.T) {
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerApprovalMode("never", ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerApprovalMode from string: %v", err)
	}
	// Polymorphic alternate loading requires type-specific handling
	_ = instance // Load succeeded, exact type depends on discriminator
	// Note: Validation skipped for polymorphic base types - test child types directly
}
