

// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"
	
	"gopkg.in/yaml.v3"
	
	"github.com/microsoft/agentschema-go/agentschema"
)


// TestMcpServerToolNeverRequireApprovalModeLoadJSON tests loading McpServerToolNeverRequireApprovalMode from JSON
func TestMcpServerToolNeverRequireApprovalModeLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "never"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}
	
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolNeverRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolNeverRequireApprovalMode: %v", err)
	}
	if instance.Kind != "never" {
		t.Errorf("Expected Kind to be "never", got %v", instance.Kind)
	}
}

// TestMcpServerToolNeverRequireApprovalModeLoadYAML tests loading McpServerToolNeverRequireApprovalMode from YAML
func TestMcpServerToolNeverRequireApprovalModeLoadYAML(t *testing.T) {
	yamlData := `
kind: never

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}
	
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolNeverRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolNeverRequireApprovalMode: %v", err)
	}
	if instance.Kind != "never" {
		t.Errorf("Expected Kind to be "never", got %v", instance.Kind)
	}
}

// TestMcpServerToolNeverRequireApprovalModeRoundtrip tests load -> save -> load produces equivalent data
func TestMcpServerToolNeverRequireApprovalModeRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "never"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}
	
	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolNeverRequireApprovalMode(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolNeverRequireApprovalMode: %v", err)
	}
	
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)
	
	reloaded, err := agentschema.LoadMcpServerToolNeverRequireApprovalMode(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload McpServerToolNeverRequireApprovalMode: %v", err)
	}
	if reloaded.Kind != "never" {
		t.Errorf("Expected Kind to be "never", got %v", reloaded.Kind)
	}
}

// TestMcpServerToolNeverRequireApprovalModeToJSON tests that ToJSON produces valid JSON
func TestMcpServerToolNeverRequireApprovalModeToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "never"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}
	
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolNeverRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolNeverRequireApprovalMode: %v", err)
	}
	
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}
	
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestMcpServerToolNeverRequireApprovalModeToYAML tests that ToYAML produces valid YAML
func TestMcpServerToolNeverRequireApprovalModeToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "never"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}
	
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolNeverRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolNeverRequireApprovalMode: %v", err)
	}
	
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}
	
	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}



