// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestMcpServerToolAlwaysRequireApprovalModeLoadJSON tests loading McpServerToolAlwaysRequireApprovalMode from JSON
func TestMcpServerToolAlwaysRequireApprovalModeLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "always"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolAlwaysRequireApprovalMode: %v", err)
	}
	if instance.Kind != "always" {
		t.Errorf(`Expected Kind to be "always", got %v`, instance.Kind)
	}
}

// TestMcpServerToolAlwaysRequireApprovalModeLoadYAML tests loading McpServerToolAlwaysRequireApprovalMode from YAML
func TestMcpServerToolAlwaysRequireApprovalModeLoadYAML(t *testing.T) {
	yamlData := `
kind: always

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolAlwaysRequireApprovalMode: %v", err)
	}
	if instance.Kind != "always" {
		t.Errorf(`Expected Kind to be "always", got %v`, instance.Kind)
	}
}

// TestMcpServerToolAlwaysRequireApprovalModeRoundtrip tests load -> save -> load produces equivalent data
func TestMcpServerToolAlwaysRequireApprovalModeRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "always"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolAlwaysRequireApprovalMode: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload McpServerToolAlwaysRequireApprovalMode: %v", err)
	}
	if reloaded.Kind != "always" {
		t.Errorf(`Expected Kind to be "always", got %v`, reloaded.Kind)
	}
}

// TestMcpServerToolAlwaysRequireApprovalModeRoundtripYAML tests YAML load -> save -> load produces equivalent data
func TestMcpServerToolAlwaysRequireApprovalModeRoundtripYAML(t *testing.T) {
	yamlData := `
kind: always

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolAlwaysRequireApprovalMode: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload McpServerToolAlwaysRequireApprovalMode: %v", err)
	}
	if reloaded.Kind != "always" {
		t.Errorf(`Expected Kind to be "always", got %v`, reloaded.Kind)
	}
}

// TestMcpServerToolAlwaysRequireApprovalModeToJSON tests that ToJSON produces valid JSON
func TestMcpServerToolAlwaysRequireApprovalModeToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "always"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolAlwaysRequireApprovalMode: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestMcpServerToolAlwaysRequireApprovalModeToYAML tests that ToYAML produces valid YAML
func TestMcpServerToolAlwaysRequireApprovalModeToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "always"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolAlwaysRequireApprovalMode: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}

// TestMcpServerToolAlwaysRequireApprovalModeLoadFromMap tests loading McpServerToolAlwaysRequireApprovalMode from an empty map
func TestMcpServerToolAlwaysRequireApprovalModeLoadFromMap(t *testing.T) {
	data := make(map[string]interface{})
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadMcpServerToolAlwaysRequireApprovalMode(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load McpServerToolAlwaysRequireApprovalMode from map: %v", err)
	}
	_ = instance // Load succeeded
}

// TestMcpServerToolAlwaysRequireApprovalModeSaveToMap tests saving McpServerToolAlwaysRequireApprovalMode to a map
func TestMcpServerToolAlwaysRequireApprovalModeSaveToMap(t *testing.T) {
	instance := agentschema.McpServerToolAlwaysRequireApprovalMode{}
	ctx := agentschema.NewSaveContext()
	data := instance.Save(ctx)
	if data == nil {
		t.Fatal("Save returned nil")
	}
}
