// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestPromptAgentLoadJSON tests loading PromptAgent from JSON
func TestPromptAgentLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "model": {
    "id": "gpt-35-turbo",
    "connection": {
      "kind": "key",
      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
      "key": "{your-api-key}"
    }
  },
  "tools": [
    {
      "name": "getCurrentWeather",
      "kind": "function",
      "description": "Get the current weather in a given location",
      "parameters": {
        "location": {
          "kind": "string",
          "description": "The city and state, e.g. San Francisco, CA"
        },
        "unit": {
          "kind": "string",
          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"
        }
      }
    }
  ],
  "template": {
    "format": "mustache",
    "parser": "prompty"
  },
  "instructions": "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}
	if instance.Kind != "prompt" {
		t.Errorf("Expected Kind to be \"prompt\", got %v", instance.Kind)
	}
	if instance.Instructions != "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}" {
		t.Errorf("Expected Instructions to be \"system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}\", got %v", instance.Instructions)
	}
}

// TestPromptAgentLoadYAML tests loading PromptAgent from YAML
func TestPromptAgentLoadYAML(t *testing.T) {
	yamlData := `
kind: prompt
model:
  id: gpt-35-turbo
  connection:
    kind: key
    endpoint: https://{your-custom-endpoint}.openai.azure.com/
    key: "{your-api-key}"
tools:
  - name: getCurrentWeather
    kind: function
    description: Get the current weather in a given location
    parameters:
      location:
        kind: string
        description: The city and state, e.g. San Francisco, CA
      unit:
        kind: string
        description: The unit of temperature, e.g. Celsius or Fahrenheit
template:
  format: mustache
  parser: prompty
instructions: |-
  system:
  You are an AI assistant who helps people find information.
  As the assistant, you answer questions briefly, succinctly,
  and in a personable manner using markdown and even add some 
  personal flair with appropriate emojis.

  # Customer
  You are helping {{firstName}} {{lastName}} to find answers to 
  their questions. Use their name to address them in your responses.
  user:
  {{question}}

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}
	if instance.Kind != "prompt" {
		t.Errorf("Expected Kind to be \"prompt\", got %v", instance.Kind)
	}
	if instance.Instructions != "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}" {
		t.Errorf("Expected Instructions to be \"system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}\", got %v", instance.Instructions)
	}
}

// TestPromptAgentRoundtrip tests load -> save -> load produces equivalent data
func TestPromptAgentRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "model": {
    "id": "gpt-35-turbo",
    "connection": {
      "kind": "key",
      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
      "key": "{your-api-key}"
    }
  },
  "tools": [
    {
      "name": "getCurrentWeather",
      "kind": "function",
      "description": "Get the current weather in a given location",
      "parameters": {
        "location": {
          "kind": "string",
          "description": "The city and state, e.g. San Francisco, CA"
        },
        "unit": {
          "kind": "string",
          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"
        }
      }
    }
  ],
  "template": {
    "format": "mustache",
    "parser": "prompty"
  },
  "instructions": "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}

	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadPromptAgent(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload PromptAgent: %v", err)
	}
	if reloaded.Kind != "prompt" {
		t.Errorf("Expected Kind to be \"prompt\", got %v", reloaded.Kind)
	}
	if reloaded.Instructions != "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}" {
		t.Errorf("Expected Instructions to be \"system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}\", got %v", reloaded.Instructions)
	}
}

// TestPromptAgentToJSON tests that ToJSON produces valid JSON
func TestPromptAgentToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "model": {
    "id": "gpt-35-turbo",
    "connection": {
      "kind": "key",
      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
      "key": "{your-api-key}"
    }
  },
  "tools": [
    {
      "name": "getCurrentWeather",
      "kind": "function",
      "description": "Get the current weather in a given location",
      "parameters": {
        "location": {
          "kind": "string",
          "description": "The city and state, e.g. San Francisco, CA"
        },
        "unit": {
          "kind": "string",
          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"
        }
      }
    }
  ],
  "template": {
    "format": "mustache",
    "parser": "prompty"
  },
  "instructions": "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}

	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestPromptAgentToYAML tests that ToYAML produces valid YAML
func TestPromptAgentToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "model": {
    "id": "gpt-35-turbo",
    "connection": {
      "kind": "key",
      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
      "key": "{your-api-key}"
    }
  },
  "tools": [
    {
      "name": "getCurrentWeather",
      "kind": "function",
      "description": "Get the current weather in a given location",
      "parameters": {
        "location": {
          "kind": "string",
          "description": "The city and state, e.g. San Francisco, CA"
        },
        "unit": {
          "kind": "string",
          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"
        }
      }
    }
  ],
  "template": {
    "format": "mustache",
    "parser": "prompty"
  },
  "instructions": "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}

	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}

// TestPromptAgentLoadJSON1 tests loading PromptAgent from JSON
func TestPromptAgentLoadJSON1(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "model": {
    "id": "gpt-35-turbo",
    "connection": {
      "kind": "key",
      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
      "key": "{your-api-key}"
    }
  },
  "tools": {
    "getCurrentWeather": {
      "kind": "function",
      "description": "Get the current weather in a given location",
      "parameters": {
        "location": {
          "kind": "string",
          "description": "The city and state, e.g. San Francisco, CA"
        },
        "unit": {
          "kind": "string",
          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"
        }
      }
    }
  },
  "template": {
    "format": "mustache",
    "parser": "prompty"
  },
  "instructions": "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}
	if instance.Kind != "prompt" {
		t.Errorf("Expected Kind to be \"prompt\", got %v", instance.Kind)
	}
	if instance.Instructions != "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}" {
		t.Errorf("Expected Instructions to be \"system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}\", got %v", instance.Instructions)
	}
}

// TestPromptAgentLoadYAML1 tests loading PromptAgent from YAML
func TestPromptAgentLoadYAML1(t *testing.T) {
	yamlData := `
kind: prompt
model:
  id: gpt-35-turbo
  connection:
    kind: key
    endpoint: https://{your-custom-endpoint}.openai.azure.com/
    key: "{your-api-key}"
tools:
  getCurrentWeather:
    kind: function
    description: Get the current weather in a given location
    parameters:
      location:
        kind: string
        description: The city and state, e.g. San Francisco, CA
      unit:
        kind: string
        description: The unit of temperature, e.g. Celsius or Fahrenheit
template:
  format: mustache
  parser: prompty
instructions: |-
  system:
  You are an AI assistant who helps people find information.
  As the assistant, you answer questions briefly, succinctly,
  and in a personable manner using markdown and even add some 
  personal flair with appropriate emojis.

  # Customer
  You are helping {{firstName}} {{lastName}} to find answers to 
  their questions. Use their name to address them in your responses.
  user:
  {{question}}

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}
	if instance.Kind != "prompt" {
		t.Errorf("Expected Kind to be \"prompt\", got %v", instance.Kind)
	}
	if instance.Instructions != "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}" {
		t.Errorf("Expected Instructions to be \"system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}\", got %v", instance.Instructions)
	}
}

// TestPromptAgentRoundtrip1 tests load -> save -> load produces equivalent data
func TestPromptAgentRoundtrip1(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "model": {
    "id": "gpt-35-turbo",
    "connection": {
      "kind": "key",
      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
      "key": "{your-api-key}"
    }
  },
  "tools": {
    "getCurrentWeather": {
      "kind": "function",
      "description": "Get the current weather in a given location",
      "parameters": {
        "location": {
          "kind": "string",
          "description": "The city and state, e.g. San Francisco, CA"
        },
        "unit": {
          "kind": "string",
          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"
        }
      }
    }
  },
  "template": {
    "format": "mustache",
    "parser": "prompty"
  },
  "instructions": "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}

	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadPromptAgent(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload PromptAgent: %v", err)
	}
	if reloaded.Kind != "prompt" {
		t.Errorf("Expected Kind to be \"prompt\", got %v", reloaded.Kind)
	}
	if reloaded.Instructions != "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}" {
		t.Errorf("Expected Instructions to be \"system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}\", got %v", reloaded.Instructions)
	}
}

// TestPromptAgentToJSON1 tests that ToJSON produces valid JSON
func TestPromptAgentToJSON1(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "model": {
    "id": "gpt-35-turbo",
    "connection": {
      "kind": "key",
      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
      "key": "{your-api-key}"
    }
  },
  "tools": {
    "getCurrentWeather": {
      "kind": "function",
      "description": "Get the current weather in a given location",
      "parameters": {
        "location": {
          "kind": "string",
          "description": "The city and state, e.g. San Francisco, CA"
        },
        "unit": {
          "kind": "string",
          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"
        }
      }
    }
  },
  "template": {
    "format": "mustache",
    "parser": "prompty"
  },
  "instructions": "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}

	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestPromptAgentToYAML1 tests that ToYAML produces valid YAML
func TestPromptAgentToYAML1(t *testing.T) {
	jsonData := `
{
  "kind": "prompt",
  "model": {
    "id": "gpt-35-turbo",
    "connection": {
      "kind": "key",
      "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
      "key": "{your-api-key}"
    }
  },
  "tools": {
    "getCurrentWeather": {
      "kind": "function",
      "description": "Get the current weather in a given location",
      "parameters": {
        "location": {
          "kind": "string",
          "description": "The city and state, e.g. San Francisco, CA"
        },
        "unit": {
          "kind": "string",
          "description": "The unit of temperature, e.g. Celsius or Fahrenheit"
        }
      }
    }
  },
  "template": {
    "format": "mustache",
    "parser": "prompty"
  },
  "instructions": "system:\nYou are an AI assistant who helps people find information.\nAs the assistant, you answer questions briefly, succinctly,\nand in a personable manner using markdown and even add some \npersonal flair with appropriate emojis.\n\n# Customer\nYou are helping {{firstName}} {{lastName}} to find answers to \ntheir questions. Use their name to address them in your responses.\nuser:\n{{question}}"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadPromptAgent(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load PromptAgent: %v", err)
	}

	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
