// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestProtocolVersionRecordLoadJSON tests loading ProtocolVersionRecord from JSON
func TestProtocolVersionRecordLoadJSON(t *testing.T) {
	jsonData := `
{
  "protocol": "responses",
  "version": "v0.1.1"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadProtocolVersionRecord(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ProtocolVersionRecord: %v", err)
	}
	if instance.Protocol != "responses" {
		t.Errorf(`Expected Protocol to be "responses", got %v`, instance.Protocol)
	}
	if instance.Version != "v0.1.1" {
		t.Errorf(`Expected Version to be "v0.1.1", got %v`, instance.Version)
	}
}

// TestProtocolVersionRecordLoadYAML tests loading ProtocolVersionRecord from YAML
func TestProtocolVersionRecordLoadYAML(t *testing.T) {
	yamlData := `
protocol: responses
version: v0.1.1

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadProtocolVersionRecord(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ProtocolVersionRecord: %v", err)
	}
	if instance.Protocol != "responses" {
		t.Errorf(`Expected Protocol to be "responses", got %v`, instance.Protocol)
	}
	if instance.Version != "v0.1.1" {
		t.Errorf(`Expected Version to be "v0.1.1", got %v`, instance.Version)
	}
}

// TestProtocolVersionRecordRoundtrip tests load -> save -> load produces equivalent data
func TestProtocolVersionRecordRoundtrip(t *testing.T) {
	jsonData := `
{
  "protocol": "responses",
  "version": "v0.1.1"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadProtocolVersionRecord(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ProtocolVersionRecord: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadProtocolVersionRecord(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ProtocolVersionRecord: %v", err)
	}
	if reloaded.Protocol != "responses" {
		t.Errorf(`Expected Protocol to be "responses", got %v`, reloaded.Protocol)
	}
	if reloaded.Version != "v0.1.1" {
		t.Errorf(`Expected Version to be "v0.1.1", got %v`, reloaded.Version)
	}
}

// TestProtocolVersionRecordRoundtripYAML tests YAML load -> save -> load produces equivalent data
func TestProtocolVersionRecordRoundtripYAML(t *testing.T) {
	yamlData := `
protocol: responses
version: v0.1.1

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadProtocolVersionRecord(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ProtocolVersionRecord: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadProtocolVersionRecord(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ProtocolVersionRecord: %v", err)
	}
	if reloaded.Protocol != "responses" {
		t.Errorf(`Expected Protocol to be "responses", got %v`, reloaded.Protocol)
	}
	if reloaded.Version != "v0.1.1" {
		t.Errorf(`Expected Version to be "v0.1.1", got %v`, reloaded.Version)
	}
}

// TestProtocolVersionRecordToJSON tests that ToJSON produces valid JSON
func TestProtocolVersionRecordToJSON(t *testing.T) {
	jsonData := `
{
  "protocol": "responses",
  "version": "v0.1.1"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadProtocolVersionRecord(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ProtocolVersionRecord: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestProtocolVersionRecordToYAML tests that ToYAML produces valid YAML
func TestProtocolVersionRecordToYAML(t *testing.T) {
	jsonData := `
{
  "protocol": "responses",
  "version": "v0.1.1"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadProtocolVersionRecord(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ProtocolVersionRecord: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}

// TestProtocolVersionRecordLoadFromMap tests loading ProtocolVersionRecord from an empty map
func TestProtocolVersionRecordLoadFromMap(t *testing.T) {
	data := make(map[string]interface{})
	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadProtocolVersionRecord(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ProtocolVersionRecord from map: %v", err)
	}
	_ = instance // Load succeeded
}

// TestProtocolVersionRecordSaveToMap tests saving ProtocolVersionRecord to a map
func TestProtocolVersionRecordSaveToMap(t *testing.T) {
	instance := agentschema.ProtocolVersionRecord{}
	ctx := agentschema.NewSaveContext()
	data := instance.Save(ctx)
	if data == nil {
		t.Fatal("Save returned nil")
	}
}
