// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestToolLoadJSON tests loading Tool from JSON
func TestToolLoadJSON(t *testing.T) {
	jsonData := `
{
  "name": "my-tool",
  "kind": "function",
  "description": "A description of the tool",
  "bindings": {
    "input": "value"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load Tool: %v", err)
	}
	if instance.Name != "my-tool" {
		t.Errorf("Expected Name to be \"my-tool\", got %v", instance.Name)
	}
	if instance.Kind != "function" {
		t.Errorf("Expected Kind to be \"function\", got %v", instance.Kind)
	}
	if instance.Description != "A description of the tool" {
		t.Errorf("Expected Description to be \"A description of the tool\", got %v", instance.Description)
	}
}

// TestToolLoadYAML tests loading Tool from YAML
func TestToolLoadYAML(t *testing.T) {
	yamlData := `
name: my-tool
kind: function
description: A description of the tool
bindings:
  input: value

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load Tool: %v", err)
	}
	if instance.Name != "my-tool" {
		t.Errorf("Expected Name to be \"my-tool\", got %v", instance.Name)
	}
	if instance.Kind != "function" {
		t.Errorf("Expected Kind to be \"function\", got %v", instance.Kind)
	}
	if instance.Description != "A description of the tool" {
		t.Errorf("Expected Description to be \"A description of the tool\", got %v", instance.Description)
	}
}

// TestToolRoundtrip tests load -> save -> load produces equivalent data
func TestToolRoundtrip(t *testing.T) {
	jsonData := `
{
  "name": "my-tool",
  "kind": "function",
  "description": "A description of the tool",
  "bindings": {
    "input": "value"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadTool(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load Tool: %v", err)
	}

	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadTool(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload Tool: %v", err)
	}
	if reloaded.Name != "my-tool" {
		t.Errorf("Expected Name to be \"my-tool\", got %v", reloaded.Name)
	}
	if reloaded.Kind != "function" {
		t.Errorf("Expected Kind to be \"function\", got %v", reloaded.Kind)
	}
	if reloaded.Description != "A description of the tool" {
		t.Errorf("Expected Description to be \"A description of the tool\", got %v", reloaded.Description)
	}
}

// TestToolToJSON tests that ToJSON produces valid JSON
func TestToolToJSON(t *testing.T) {
	jsonData := `
{
  "name": "my-tool",
  "kind": "function",
  "description": "A description of the tool",
  "bindings": {
    "input": "value"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load Tool: %v", err)
	}

	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestToolToYAML tests that ToYAML produces valid YAML
func TestToolToYAML(t *testing.T) {
	jsonData := `
{
  "name": "my-tool",
  "kind": "function",
  "description": "A description of the tool",
  "bindings": {
    "input": "value"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load Tool: %v", err)
	}

	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
