// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestToolResourceLoadJSON tests loading ToolResource from JSON
func TestToolResourceLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "tool",
  "id": "web-search",
  "options": {
    "myToolResourceProperty": "myValue"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadToolResource(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolResource: %v", err)
	}
	if instance.Kind != "tool" {
		t.Errorf(`Expected Kind to be "tool", got %v`, instance.Kind)
	}
	if instance.Id != "web-search" {
		t.Errorf(`Expected Id to be "web-search", got %v`, instance.Id)
	}
}

// TestToolResourceLoadYAML tests loading ToolResource from YAML
func TestToolResourceLoadYAML(t *testing.T) {
	yamlData := `
kind: tool
id: web-search
options:
  myToolResourceProperty: myValue

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadToolResource(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolResource: %v", err)
	}
	if instance.Kind != "tool" {
		t.Errorf(`Expected Kind to be "tool", got %v`, instance.Kind)
	}
	if instance.Id != "web-search" {
		t.Errorf(`Expected Id to be "web-search", got %v`, instance.Id)
	}
}

// TestToolResourceRoundtrip tests load -> save -> load produces equivalent data
func TestToolResourceRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "tool",
  "id": "web-search",
  "options": {
    "myToolResourceProperty": "myValue"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadToolResource(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load ToolResource: %v", err)
	}
	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadToolResource(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload ToolResource: %v", err)
	}
	if reloaded.Kind != "tool" {
		t.Errorf(`Expected Kind to be "tool", got %v`, reloaded.Kind)
	}
	if reloaded.Id != "web-search" {
		t.Errorf(`Expected Id to be "web-search", got %v`, reloaded.Id)
	}
}

// TestToolResourceToJSON tests that ToJSON produces valid JSON
func TestToolResourceToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "tool",
  "id": "web-search",
  "options": {
    "myToolResourceProperty": "myValue"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadToolResource(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolResource: %v", err)
	}
	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestToolResourceToYAML tests that ToYAML produces valid YAML
func TestToolResourceToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "tool",
  "id": "web-search",
  "options": {
    "myToolResourceProperty": "myValue"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadToolResource(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load ToolResource: %v", err)
	}
	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
