// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestWebSearchToolLoadJSON tests loading WebSearchTool from JSON
func TestWebSearchToolLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "bing_search",
  "connection": {
    "kind": "reference"
  },
  "options": {
    "instanceName": "MyBingInstance",
    "market": "en-US",
    "setLang": "en",
    "count": 10,
    "freshness": "Day"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWebSearchTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load WebSearchTool: %v", err)
	}
	if instance.Kind != "bing_search" {
		t.Errorf("Expected Kind to be \"bing_search\", got %v", instance.Kind)
	}
}

// TestWebSearchToolLoadYAML tests loading WebSearchTool from YAML
func TestWebSearchToolLoadYAML(t *testing.T) {
	yamlData := `
kind: bing_search
connection:
  kind: reference
options:
  instanceName: MyBingInstance
  market: en-US
  setLang: en
  count: 10
  freshness: Day

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWebSearchTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load WebSearchTool: %v", err)
	}
	if instance.Kind != "bing_search" {
		t.Errorf("Expected Kind to be \"bing_search\", got %v", instance.Kind)
	}
}

// TestWebSearchToolRoundtrip tests load -> save -> load produces equivalent data
func TestWebSearchToolRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "bing_search",
  "connection": {
    "kind": "reference"
  },
  "options": {
    "instanceName": "MyBingInstance",
    "market": "en-US",
    "setLang": "en",
    "count": 10,
    "freshness": "Day"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWebSearchTool(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load WebSearchTool: %v", err)
	}

	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadWebSearchTool(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload WebSearchTool: %v", err)
	}
	if reloaded.Kind != "bing_search" {
		t.Errorf("Expected Kind to be \"bing_search\", got %v", reloaded.Kind)
	}
}

// TestWebSearchToolToJSON tests that ToJSON produces valid JSON
func TestWebSearchToolToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "bing_search",
  "connection": {
    "kind": "reference"
  },
  "options": {
    "instanceName": "MyBingInstance",
    "market": "en-US",
    "setLang": "en",
    "count": 10,
    "freshness": "Day"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWebSearchTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load WebSearchTool: %v", err)
	}

	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestWebSearchToolToYAML tests that ToYAML produces valid YAML
func TestWebSearchToolToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "bing_search",
  "connection": {
    "kind": "reference"
  },
  "options": {
    "instanceName": "MyBingInstance",
    "market": "en-US",
    "setLang": "en",
    "count": 10,
    "freshness": "Day"
  }
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWebSearchTool(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load WebSearchTool: %v", err)
	}

	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
