// Code generated by AgentSchema emitter; DO NOT EDIT.

package agentschema_test

import (
	"encoding/json"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/microsoft/agentschema-go/agentschema"
)

// TestWorkflowLoadJSON tests loading Workflow from JSON
func TestWorkflowLoadJSON(t *testing.T) {
	jsonData := `
{
  "kind": "workflow"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWorkflow(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load Workflow: %v", err)
	}
	if instance.Kind != "workflow" {
		t.Errorf(`Expected Kind to be "workflow", got %v`, instance.Kind)
	}
}

// TestWorkflowLoadYAML tests loading Workflow from YAML
func TestWorkflowLoadYAML(t *testing.T) {
	yamlData := `
kind: workflow

`
	var data map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlData), &data); err != nil {
		t.Fatalf("Failed to parse YAML: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWorkflow(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load Workflow: %v", err)
	}
	if instance.Kind != "workflow" {
		t.Errorf(`Expected Kind to be "workflow", got %v`, instance.Kind)
	}
}

// TestWorkflowRoundtrip tests load -> save -> load produces equivalent data
func TestWorkflowRoundtrip(t *testing.T) {
	jsonData := `
{
  "kind": "workflow"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	loadCtx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWorkflow(data, loadCtx)
	if err != nil {
		t.Fatalf("Failed to load Workflow: %v", err)
	}

	saveCtx := agentschema.NewSaveContext()
	savedData := instance.Save(saveCtx)

	reloaded, err := agentschema.LoadWorkflow(savedData, loadCtx)
	if err != nil {
		t.Fatalf("Failed to reload Workflow: %v", err)
	}
	if reloaded.Kind != "workflow" {
		t.Errorf(`Expected Kind to be "workflow", got %v`, reloaded.Kind)
	}
}

// TestWorkflowToJSON tests that ToJSON produces valid JSON
func TestWorkflowToJSON(t *testing.T) {
	jsonData := `
{
  "kind": "workflow"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWorkflow(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load Workflow: %v", err)
	}

	jsonOutput, err := instance.ToJSON()
	if err != nil {
		t.Fatalf("Failed to convert to JSON: %v", err)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated JSON: %v", err)
	}
}

// TestWorkflowToYAML tests that ToYAML produces valid YAML
func TestWorkflowToYAML(t *testing.T) {
	jsonData := `
{
  "kind": "workflow"
}
`
	var data map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &data); err != nil {
		t.Fatalf("Failed to parse JSON: %v", err)
	}

	ctx := agentschema.NewLoadContext()
	instance, err := agentschema.LoadWorkflow(data, ctx)
	if err != nil {
		t.Fatalf("Failed to load Workflow: %v", err)
	}

	yamlOutput, err := instance.ToYAML()
	if err != nil {
		t.Fatalf("Failed to convert to YAML: %v", err)
	}

	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(yamlOutput), &parsed); err != nil {
		t.Fatalf("Failed to parse generated YAML: %v", err)
	}
}
