// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_agent_definition_load_json() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let instance =
        AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_agent_definition_load_yaml() {
    let yaml_data = r####"
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    answer:
      kind: string
      description: The answer to the user's question.

"####;
    let instance =
        AgentDefinition::from_yaml(yaml_data).expect("Failed to load AgentDefinition from YAML");
    let _ = instance;
}

#[test]
fn test_agent_definition_roundtrip() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_to_json() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_to_yaml() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_load_json_1() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let instance =
        AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_agent_definition_load_yaml_1() {
    let yaml_data = r####"
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    - name: answer
      kind: string
      description: The answer to the user's question.

"####;
    let instance =
        AgentDefinition::from_yaml(yaml_data).expect("Failed to load AgentDefinition from YAML");
    let _ = instance;
}

#[test]
fn test_agent_definition_roundtrip_1() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_to_json_1() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_to_yaml_1() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_load_json_2() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let instance =
        AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_agent_definition_load_yaml_2() {
    let yaml_data = r####"
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    answer:
      kind: string
      description: The answer to the user's question.

"####;
    let instance =
        AgentDefinition::from_yaml(yaml_data).expect("Failed to load AgentDefinition from YAML");
    let _ = instance;
}

#[test]
fn test_agent_definition_roundtrip_2() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_to_json_2() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_to_yaml_2() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_load_json_3() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let instance =
        AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_agent_definition_load_yaml_3() {
    let yaml_data = r####"
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    - name: answer
      kind: string
      description: The answer to the user's question.

"####;
    let instance =
        AgentDefinition::from_yaml(yaml_data).expect("Failed to load AgentDefinition from YAML");
    let _ = instance;
}

#[test]
fn test_agent_definition_roundtrip_3() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_to_json_3() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}

#[test]
fn test_agent_definition_to_yaml_3() {
    let json_data = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let instance = AgentDefinition::from_json(json_data).expect("Failed to load AgentDefinition");
    let _ = instance;
}
