// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::AgentDefinition;

#[test]
fn test_agent_definition_load_json() {
    let json = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let result = AgentDefinition::from_json(json);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
}

#[test]
fn test_agent_definition_load_yaml() {
    let yaml = r####"
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    answer:
      kind: string
      description: The answer to the user's question.

"####;
    let result = AgentDefinition::from_yaml(yaml);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
}

#[test]
fn test_agent_definition_roundtrip() {
    let json = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let result = AgentDefinition::from_json(json);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
}

#[test]
fn test_agent_definition_load_json_1() {
    let json = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let result = AgentDefinition::from_json(json);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
}

#[test]
fn test_agent_definition_load_yaml_1() {
    let yaml = r####"
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    - name: answer
      kind: string
      description: The answer to the user's question.

"####;
    let result = AgentDefinition::from_yaml(yaml);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
}

#[test]
fn test_agent_definition_roundtrip_1() {
    let json = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let result = AgentDefinition::from_json(json);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
}

#[test]
fn test_agent_definition_load_json_2() {
    let json = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let result = AgentDefinition::from_json(json);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
}

#[test]
fn test_agent_definition_load_yaml_2() {
    let yaml = r####"
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    answer:
      kind: string
      description: The answer to the user's question.

"####;
    let result = AgentDefinition::from_yaml(yaml);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
}

#[test]
fn test_agent_definition_roundtrip_2() {
    let json = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": {
      "answer": {
        "kind": "string",
        "description": "The answer to the user's question."
      }
    }
  }
}
"####;
    let result = AgentDefinition::from_json(json);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
}

#[test]
fn test_agent_definition_load_json_3() {
    let json = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let result = AgentDefinition::from_json(json);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
}

#[test]
fn test_agent_definition_load_yaml_3() {
    let yaml = r####"
kind: prompt
name: basic-prompt
displayName: Basic Prompt Agent
description: A basic prompt that uses the GPT-3 chat API to answer questions
metadata:
  authors:
    - sethjuarez
    - jietong
  tags:
    - example
    - prompt
inputSchema:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
outputSchema:
  properties:
    - name: answer
      kind: string
      description: The answer to the user's question.

"####;
    let result = AgentDefinition::from_yaml(yaml);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
}

#[test]
fn test_agent_definition_roundtrip_3() {
    let json = r####"
{
  "kind": "prompt",
  "name": "basic-prompt",
  "displayName": "Basic Prompt Agent",
  "description": "A basic prompt that uses the GPT-3 chat API to answer questions",
  "metadata": {
    "authors": [
      "sethjuarez",
      "jietong"
    ],
    "tags": [
      "example",
      "prompt"
    ]
  },
  "inputSchema": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "outputSchema": {
    "properties": [
      {
        "name": "answer",
        "kind": "string",
        "description": "The answer to the user's question."
      }
    ]
  }
}
"####;
    let result = AgentDefinition::from_json(json);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
}
