// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_anonymous_connection_load_json() {
    let json_data = r####"
{
  "kind": "anonymous",
  "endpoint": "https://{your-custom-endpoint}.openai.azure.com/"
}
"####;
    let instance = AnonymousConnection::from_json(json_data)
        .expect("Failed to load AnonymousConnection from JSON");
    assert_eq!(instance.kind, "anonymous");
    assert_eq!(
        instance.endpoint,
        "https://{your-custom-endpoint}.openai.azure.com/"
    );
}

#[test]
fn test_anonymous_connection_load_yaml() {
    let yaml_data = r####"
kind: anonymous
endpoint: "https://{your-custom-endpoint}.openai.azure.com/"

"####;
    let instance = AnonymousConnection::from_yaml(yaml_data)
        .expect("Failed to load AnonymousConnection from YAML");
    assert_eq!(instance.kind, "anonymous");
    assert_eq!(
        instance.endpoint,
        "https://{your-custom-endpoint}.openai.azure.com/"
    );
}

#[test]
fn test_anonymous_connection_roundtrip() {
    let json_data = r####"
{
  "kind": "anonymous",
  "endpoint": "https://{your-custom-endpoint}.openai.azure.com/"
}
"####;
    let instance =
        AnonymousConnection::from_json(json_data).expect("Failed to load AnonymousConnection");
    let json_out = instance
        .to_json()
        .expect("Failed to serialize AnonymousConnection to JSON");
    let reloaded = AnonymousConnection::from_json(&json_out)
        .expect("Failed to reload AnonymousConnection from JSON");
    assert_eq!(reloaded.kind, "anonymous");
    assert_eq!(
        reloaded.endpoint,
        "https://{your-custom-endpoint}.openai.azure.com/"
    );
}

#[test]
fn test_anonymous_connection_to_json() {
    let json_data = r####"
{
  "kind": "anonymous",
  "endpoint": "https://{your-custom-endpoint}.openai.azure.com/"
}
"####;
    let instance =
        AnonymousConnection::from_json(json_data).expect("Failed to load AnonymousConnection");
    let json_out = instance
        .to_json()
        .expect("Failed to convert AnonymousConnection to JSON");
    // Verify the output is valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_out).expect("Generated JSON is not valid");
}

#[test]
fn test_anonymous_connection_to_yaml() {
    let json_data = r####"
{
  "kind": "anonymous",
  "endpoint": "https://{your-custom-endpoint}.openai.azure.com/"
}
"####;
    let instance =
        AnonymousConnection::from_json(json_data).expect("Failed to load AnonymousConnection");
    let yaml_out = instance
        .to_yaml()
        .expect("Failed to convert AnonymousConnection to YAML");
    // Verify the output is valid YAML by re-loading
    let _: serde_json::Value =
        serde_yaml::from_str(&yaml_out).expect("Generated YAML is not valid");
}
