// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_array_property_load_json() {
    let json_data = r####"
{
  "items": {
    "kind": "string"
  }
}
"####;
    let instance =
        ArrayProperty::from_json(json_data).expect("Failed to load ArrayProperty from JSON");
    let _ = instance; // No scalar properties to validate
}

#[test]
fn test_array_property_load_yaml() {
    let yaml_data = r####"
items:
  kind: string

"####;
    let instance =
        ArrayProperty::from_yaml(yaml_data).expect("Failed to load ArrayProperty from YAML");
    let _ = instance;
}

#[test]
fn test_array_property_roundtrip() {
    let json_data = r####"
{
  "items": {
    "kind": "string"
  }
}
"####;
    let instance = ArrayProperty::from_json(json_data).expect("Failed to load ArrayProperty");
    let json_out = instance
        .to_json()
        .expect("Failed to serialize ArrayProperty to JSON");
    let reloaded =
        ArrayProperty::from_json(&json_out).expect("Failed to reload ArrayProperty from JSON");
    let _ = reloaded;
}

#[test]
fn test_array_property_to_json() {
    let json_data = r####"
{
  "items": {
    "kind": "string"
  }
}
"####;
    let instance = ArrayProperty::from_json(json_data).expect("Failed to load ArrayProperty");
    let json_out = instance
        .to_json()
        .expect("Failed to convert ArrayProperty to JSON");
    // Verify the output is valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_out).expect("Generated JSON is not valid");
}

#[test]
fn test_array_property_to_yaml() {
    let json_data = r####"
{
  "items": {
    "kind": "string"
  }
}
"####;
    let instance = ArrayProperty::from_json(json_data).expect("Failed to load ArrayProperty");
    let yaml_out = instance
        .to_yaml()
        .expect("Failed to convert ArrayProperty to YAML");
    // Verify the output is valid YAML by re-loading
    let _: serde_json::Value =
        serde_yaml::from_str(&yaml_out).expect("Generated YAML is not valid");
}
