// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_container_agent_load_json() {
    let json_data = r####"
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
"####;
    let instance =
        ContainerAgent::from_json(json_data).expect("Failed to load ContainerAgent from JSON");
    assert_eq!(instance.kind, "hosted");
}

#[test]
fn test_container_agent_load_yaml() {
    let yaml_data = r####"
kind: hosted
protocols:
  - protocol: responses
    version: v0.1.1
environmentVariables:
  - name: MY_ENV_VAR
    value: my-value

"####;
    let instance =
        ContainerAgent::from_yaml(yaml_data).expect("Failed to load ContainerAgent from YAML");
    assert_eq!(instance.kind, "hosted");
}

#[test]
fn test_container_agent_roundtrip() {
    let json_data = r####"
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
"####;
    let instance = ContainerAgent::from_json(json_data).expect("Failed to load ContainerAgent");
    let json_out = instance
        .to_json()
        .expect("Failed to serialize ContainerAgent to JSON");
    let reloaded =
        ContainerAgent::from_json(&json_out).expect("Failed to reload ContainerAgent from JSON");
    assert_eq!(reloaded.kind, "hosted");
}

#[test]
fn test_container_agent_to_json() {
    let json_data = r####"
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
"####;
    let instance = ContainerAgent::from_json(json_data).expect("Failed to load ContainerAgent");
    let json_out = instance
        .to_json()
        .expect("Failed to convert ContainerAgent to JSON");
    // Verify the output is valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_out).expect("Generated JSON is not valid");
}

#[test]
fn test_container_agent_to_yaml() {
    let json_data = r####"
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
"####;
    let instance = ContainerAgent::from_json(json_data).expect("Failed to load ContainerAgent");
    let yaml_out = instance
        .to_yaml()
        .expect("Failed to convert ContainerAgent to YAML");
    // Verify the output is valid YAML by re-loading
    let _: serde_json::Value =
        serde_yaml::from_str(&yaml_out).expect("Generated YAML is not valid");
}
