// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_format_load_json() {
    let json_data = r####"
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
"####;
    let instance = Format::from_json(json_data).expect("Failed to load Format from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_format_load_yaml() {
    let yaml_data = r####"
kind: mustache
strict: true
options:
  key: value

"####;
    let instance = Format::from_yaml(yaml_data).expect("Failed to load Format from YAML");
    let _ = instance;
}

#[test]
fn test_format_roundtrip() {
    let json_data = r####"
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
"####;
    let instance = Format::from_json(json_data).expect("Failed to load Format");
    let _ = instance;
}

#[test]
fn test_format_to_json() {
    let json_data = r####"
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
"####;
    let instance = Format::from_json(json_data).expect("Failed to load Format");
    let _ = instance;
}

#[test]
fn test_format_to_yaml() {
    let json_data = r####"
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
"####;
    let instance = Format::from_json(json_data).expect("Failed to load Format");
    let _ = instance;
}

#[test]
fn test_format_from_format() {
    // Test shorthand: String -> Format
    let json_input = r####""example""####;
    let instance = Format::from_json(json_input).expect("Failed to load Format from String");
    let _ = instance;
}
