// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_function_tool_load_json() {
    let json_data = r####"
{
  "kind": "function",
  "parameters": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "strict": true
}
"####;
    let instance =
        FunctionTool::from_json(json_data).expect("Failed to load FunctionTool from JSON");
    assert_eq!(instance.kind, "function");
    assert_eq!(instance.strict, Some(true));
}

#[test]
fn test_function_tool_load_yaml() {
    let yaml_data = r####"
kind: function
parameters:
  properties:
    firstName:
      kind: string
      value: Jane
    lastName:
      kind: string
      value: Doe
    question:
      kind: string
      value: What is the meaning of life?
strict: true

"####;
    let instance =
        FunctionTool::from_yaml(yaml_data).expect("Failed to load FunctionTool from YAML");
    assert_eq!(instance.kind, "function");
    assert_eq!(instance.strict, Some(true));
}

#[test]
fn test_function_tool_roundtrip() {
    let json_data = r####"
{
  "kind": "function",
  "parameters": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "strict": true
}
"####;
    let instance = FunctionTool::from_json(json_data).expect("Failed to load FunctionTool");
    let json_out = instance
        .to_json()
        .expect("Failed to serialize FunctionTool to JSON");
    let reloaded =
        FunctionTool::from_json(&json_out).expect("Failed to reload FunctionTool from JSON");
    assert_eq!(reloaded.kind, "function");
    assert_eq!(reloaded.strict, Some(true));
}

#[test]
fn test_function_tool_to_json() {
    let json_data = r####"
{
  "kind": "function",
  "parameters": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "strict": true
}
"####;
    let instance = FunctionTool::from_json(json_data).expect("Failed to load FunctionTool");
    let json_out = instance
        .to_json()
        .expect("Failed to convert FunctionTool to JSON");
    // Verify the output is valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_out).expect("Generated JSON is not valid");
}

#[test]
fn test_function_tool_to_yaml() {
    let json_data = r####"
{
  "kind": "function",
  "parameters": {
    "properties": {
      "firstName": {
        "kind": "string",
        "value": "Jane"
      },
      "lastName": {
        "kind": "string",
        "value": "Doe"
      },
      "question": {
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    }
  },
  "strict": true
}
"####;
    let instance = FunctionTool::from_json(json_data).expect("Failed to load FunctionTool");
    let yaml_out = instance
        .to_yaml()
        .expect("Failed to convert FunctionTool to YAML");
    // Verify the output is valid YAML by re-loading
    let _: serde_json::Value =
        serde_yaml::from_str(&yaml_out).expect("Generated YAML is not valid");
}

#[test]
fn test_function_tool_load_json_1() {
    let json_data = r####"
{
  "kind": "function",
  "parameters": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "strict": true
}
"####;
    let instance =
        FunctionTool::from_json(json_data).expect("Failed to load FunctionTool from JSON");
    assert_eq!(instance.kind, "function");
    assert_eq!(instance.strict, Some(true));
}

#[test]
fn test_function_tool_load_yaml_1() {
    let yaml_data = r####"
kind: function
parameters:
  properties:
    - name: firstName
      kind: string
      value: Jane
    - name: lastName
      kind: string
      value: Doe
    - name: question
      kind: string
      value: What is the meaning of life?
strict: true

"####;
    let instance =
        FunctionTool::from_yaml(yaml_data).expect("Failed to load FunctionTool from YAML");
    assert_eq!(instance.kind, "function");
    assert_eq!(instance.strict, Some(true));
}

#[test]
fn test_function_tool_roundtrip_1() {
    let json_data = r####"
{
  "kind": "function",
  "parameters": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "strict": true
}
"####;
    let instance = FunctionTool::from_json(json_data).expect("Failed to load FunctionTool");
    let json_out = instance
        .to_json()
        .expect("Failed to serialize FunctionTool to JSON");
    let reloaded =
        FunctionTool::from_json(&json_out).expect("Failed to reload FunctionTool from JSON");
    assert_eq!(reloaded.kind, "function");
    assert_eq!(reloaded.strict, Some(true));
}

#[test]
fn test_function_tool_to_json_1() {
    let json_data = r####"
{
  "kind": "function",
  "parameters": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "strict": true
}
"####;
    let instance = FunctionTool::from_json(json_data).expect("Failed to load FunctionTool");
    let json_out = instance
        .to_json()
        .expect("Failed to convert FunctionTool to JSON");
    // Verify the output is valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_out).expect("Generated JSON is not valid");
}

#[test]
fn test_function_tool_to_yaml_1() {
    let json_data = r####"
{
  "kind": "function",
  "parameters": {
    "properties": [
      {
        "name": "firstName",
        "kind": "string",
        "value": "Jane"
      },
      {
        "name": "lastName",
        "kind": "string",
        "value": "Doe"
      },
      {
        "name": "question",
        "kind": "string",
        "value": "What is the meaning of life?"
      }
    ]
  },
  "strict": true
}
"####;
    let instance = FunctionTool::from_json(json_data).expect("Failed to load FunctionTool");
    let yaml_out = instance
        .to_yaml()
        .expect("Failed to convert FunctionTool to YAML");
    // Verify the output is valid YAML by re-loading
    let _: serde_json::Value =
        serde_yaml::from_str(&yaml_out).expect("Generated YAML is not valid");
}
