// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_mcp_tool_load_json() {
    let json_data = r####"
{
  "kind": "mcp",
  "connection": {
    "kind": "reference"
  },
  "serverName": "My MCP Server",
  "serverDescription": "This tool allows access to MCP services.",
  "approvalMode": {
    "kind": "always"
  },
  "allowedTools": [
    "operation1",
    "operation2"
  ]
}
"####;
    let instance = McpTool::from_json(json_data).expect("Failed to load McpTool from JSON");
    assert_eq!(instance.kind, "mcp");
    assert_eq!(instance.server_name, "My MCP Server");
    assert_eq!(
        instance.server_description.as_deref(),
        Some("This tool allows access to MCP services.")
    );
}

#[test]
fn test_mcp_tool_load_yaml() {
    let yaml_data = r####"
kind: mcp
connection:
  kind: reference
serverName: My MCP Server
serverDescription: This tool allows access to MCP services.
approvalMode:
  kind: always
allowedTools:
  - operation1
  - operation2

"####;
    let instance = McpTool::from_yaml(yaml_data).expect("Failed to load McpTool from YAML");
    assert_eq!(instance.kind, "mcp");
    assert_eq!(instance.server_name, "My MCP Server");
    assert_eq!(
        instance.server_description.as_deref(),
        Some("This tool allows access to MCP services.")
    );
}

#[test]
fn test_mcp_tool_roundtrip() {
    let json_data = r####"
{
  "kind": "mcp",
  "connection": {
    "kind": "reference"
  },
  "serverName": "My MCP Server",
  "serverDescription": "This tool allows access to MCP services.",
  "approvalMode": {
    "kind": "always"
  },
  "allowedTools": [
    "operation1",
    "operation2"
  ]
}
"####;
    let instance = McpTool::from_json(json_data).expect("Failed to load McpTool");
    let json_out = instance
        .to_json()
        .expect("Failed to serialize McpTool to JSON");
    let reloaded = McpTool::from_json(&json_out).expect("Failed to reload McpTool from JSON");
    assert_eq!(reloaded.kind, "mcp");
    assert_eq!(reloaded.server_name, "My MCP Server");
    assert_eq!(
        reloaded.server_description.as_deref(),
        Some("This tool allows access to MCP services.")
    );
}

#[test]
fn test_mcp_tool_to_json() {
    let json_data = r####"
{
  "kind": "mcp",
  "connection": {
    "kind": "reference"
  },
  "serverName": "My MCP Server",
  "serverDescription": "This tool allows access to MCP services.",
  "approvalMode": {
    "kind": "always"
  },
  "allowedTools": [
    "operation1",
    "operation2"
  ]
}
"####;
    let instance = McpTool::from_json(json_data).expect("Failed to load McpTool");
    let json_out = instance
        .to_json()
        .expect("Failed to convert McpTool to JSON");
    // Verify the output is valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_out).expect("Generated JSON is not valid");
}

#[test]
fn test_mcp_tool_to_yaml() {
    let json_data = r####"
{
  "kind": "mcp",
  "connection": {
    "kind": "reference"
  },
  "serverName": "My MCP Server",
  "serverDescription": "This tool allows access to MCP services.",
  "approvalMode": {
    "kind": "always"
  },
  "allowedTools": [
    "operation1",
    "operation2"
  ]
}
"####;
    let instance = McpTool::from_json(json_data).expect("Failed to load McpTool");
    let yaml_out = instance
        .to_yaml()
        .expect("Failed to convert McpTool to YAML");
    // Verify the output is valid YAML by re-loading
    let _: serde_json::Value =
        serde_yaml::from_str(&yaml_out).expect("Generated YAML is not valid");
}
