// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::McpServerApprovalMode;

#[test]
fn test_mcp_server_approval_mode_load_json() {
    let json = r####"
{
  "kind": "never"
}
"####;
    let result = McpServerApprovalMode::from_json(json);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
}

#[test]
fn test_mcp_server_approval_mode_load_yaml() {
    let yaml = r####"
kind: never

"####;
    let result = McpServerApprovalMode::from_yaml(yaml);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
}

#[test]
fn test_mcp_server_approval_mode_roundtrip() {
    let json = r####"
{
  "kind": "never"
}
"####;
    let result = McpServerApprovalMode::from_json(json);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
}

#[test]
fn test_mcp_server_approval_mode_from_kind() {
    let value = serde_json::json!("never");
    let instance = McpServerApprovalMode::load_from_value(&value);
    let _ = instance; // abstract type, load succeeded
}
