// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_model_options_load_json() {
    let json_data = r####"
{
  "frequencyPenalty": 0.5,
  "maxOutputTokens": 2048,
  "presencePenalty": 0.3,
  "seed": 42,
  "temperature": 0.7,
  "topK": 40,
  "topP": 0.9,
  "stopSequences": [
    "\n",
    "###"
  ],
  "allowMultipleToolCalls": true,
  "additionalProperties": {
    "customProperty": "value",
    "anotherProperty": "anotherValue"
  }
}
"####;
    let instance =
        ModelOptions::from_json(json_data).expect("Failed to load ModelOptions from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_model_options_load_yaml() {
    let yaml_data = r####"
frequencyPenalty: 0.5
maxOutputTokens: 2048
presencePenalty: 0.3
seed: 42
temperature: 0.7
topK: 40
topP: 0.9
stopSequences:
  - "\n"
  - "###"
allowMultipleToolCalls: true
additionalProperties:
  customProperty: value
  anotherProperty: anotherValue

"####;
    let instance =
        ModelOptions::from_yaml(yaml_data).expect("Failed to load ModelOptions from YAML");
    let _ = instance;
}

#[test]
fn test_model_options_roundtrip() {
    let json_data = r####"
{
  "frequencyPenalty": 0.5,
  "maxOutputTokens": 2048,
  "presencePenalty": 0.3,
  "seed": 42,
  "temperature": 0.7,
  "topK": 40,
  "topP": 0.9,
  "stopSequences": [
    "\n",
    "###"
  ],
  "allowMultipleToolCalls": true,
  "additionalProperties": {
    "customProperty": "value",
    "anotherProperty": "anotherValue"
  }
}
"####;
    let instance = ModelOptions::from_json(json_data).expect("Failed to load ModelOptions");
    let _ = instance;
}

#[test]
fn test_model_options_to_json() {
    let json_data = r####"
{
  "frequencyPenalty": 0.5,
  "maxOutputTokens": 2048,
  "presencePenalty": 0.3,
  "seed": 42,
  "temperature": 0.7,
  "topK": 40,
  "topP": 0.9,
  "stopSequences": [
    "\n",
    "###"
  ],
  "allowMultipleToolCalls": true,
  "additionalProperties": {
    "customProperty": "value",
    "anotherProperty": "anotherValue"
  }
}
"####;
    let instance = ModelOptions::from_json(json_data).expect("Failed to load ModelOptions");
    let _ = instance;
}

#[test]
fn test_model_options_to_yaml() {
    let json_data = r####"
{
  "frequencyPenalty": 0.5,
  "maxOutputTokens": 2048,
  "presencePenalty": 0.3,
  "seed": 42,
  "temperature": 0.7,
  "topK": 40,
  "topP": 0.9,
  "stopSequences": [
    "\n",
    "###"
  ],
  "allowMultipleToolCalls": true,
  "additionalProperties": {
    "customProperty": "value",
    "anotherProperty": "anotherValue"
  }
}
"####;
    let instance = ModelOptions::from_json(json_data).expect("Failed to load ModelOptions");
    let _ = instance;
}
