// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_parser_load_json() {
    let json_data = r####"
{
  "kind": "prompty",
  "options": {
    "key": "value"
  }
}
"####;
    let instance = Parser::from_json(json_data).expect("Failed to load Parser from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_parser_load_yaml() {
    let yaml_data = r####"
kind: prompty
options:
  key: value

"####;
    let instance = Parser::from_yaml(yaml_data).expect("Failed to load Parser from YAML");
    let _ = instance;
}

#[test]
fn test_parser_roundtrip() {
    let json_data = r####"
{
  "kind": "prompty",
  "options": {
    "key": "value"
  }
}
"####;
    let instance = Parser::from_json(json_data).expect("Failed to load Parser");
    let _ = instance;
}

#[test]
fn test_parser_to_json() {
    let json_data = r####"
{
  "kind": "prompty",
  "options": {
    "key": "value"
  }
}
"####;
    let instance = Parser::from_json(json_data).expect("Failed to load Parser");
    let _ = instance;
}

#[test]
fn test_parser_to_yaml() {
    let json_data = r####"
{
  "kind": "prompty",
  "options": {
    "key": "value"
  }
}
"####;
    let instance = Parser::from_json(json_data).expect("Failed to load Parser");
    let _ = instance;
}

#[test]
fn test_parser_from_parser() {
    // Test shorthand: String -> Parser
    let json_input = r####""example""####;
    let instance = Parser::from_json(json_input).expect("Failed to load Parser from String");
    let _ = instance;
}
