// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_property_load_json() {
    let json_data = r####"
{
  "name": "my-input",
  "kind": "string",
  "description": "A description of the input property",
  "required": true,
  "default": "default value",
  "example": "example value",
  "enumValues": [
    "value1",
    "value2",
    "value3"
  ]
}
"####;
    let instance = Property::from_json(json_data).expect("Failed to load Property from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_property_load_yaml() {
    let yaml_data = r####"
name: my-input
kind: string
description: A description of the input property
required: true
default: default value
example: example value
enumValues:
  - value1
  - value2
  - value3

"####;
    let instance = Property::from_yaml(yaml_data).expect("Failed to load Property from YAML");
    let _ = instance;
}

#[test]
fn test_property_roundtrip() {
    let json_data = r####"
{
  "name": "my-input",
  "kind": "string",
  "description": "A description of the input property",
  "required": true,
  "default": "default value",
  "example": "example value",
  "enumValues": [
    "value1",
    "value2",
    "value3"
  ]
}
"####;
    let instance = Property::from_json(json_data).expect("Failed to load Property");
    let _ = instance;
}

#[test]
fn test_property_to_json() {
    let json_data = r####"
{
  "name": "my-input",
  "kind": "string",
  "description": "A description of the input property",
  "required": true,
  "default": "default value",
  "example": "example value",
  "enumValues": [
    "value1",
    "value2",
    "value3"
  ]
}
"####;
    let instance = Property::from_json(json_data).expect("Failed to load Property");
    let _ = instance;
}

#[test]
fn test_property_to_yaml() {
    let json_data = r####"
{
  "name": "my-input",
  "kind": "string",
  "description": "A description of the input property",
  "required": true,
  "default": "default value",
  "example": "example value",
  "enumValues": [
    "value1",
    "value2",
    "value3"
  ]
}
"####;
    let instance = Property::from_json(json_data).expect("Failed to load Property");
    let _ = instance;
}

#[test]
fn test_property_from_input() {
    // Test shorthand: bool -> Property
    let json_input = r####"false"####;
    let instance = Property::from_json(json_input).expect("Failed to load Property from bool");
    let _ = instance;
}

#[test]
fn test_property_from_input_2() {
    // Test shorthand: f32 -> Property
    let json_input = r####"3.14"####;
    let instance = Property::from_json(json_input).expect("Failed to load Property from f32");
    let _ = instance;
}

#[test]
fn test_property_from_input_3() {
    // Test shorthand: integer -> Property
    let json_input = r####"4"####;
    let instance = Property::from_json(json_input).expect("Failed to load Property from integer");
    let _ = instance;
}

#[test]
fn test_property_from_input_4() {
    // Test shorthand: String -> Property
    let json_input = r####""example""####;
    let instance = Property::from_json(json_input).expect("Failed to load Property from String");
    let _ = instance;
}
