// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_remote_connection_load_json() {
    let json_data = r####"
{
  "kind": "remote",
  "name": "my-reference-connection",
  "endpoint": "https://{your-custom-endpoint}.openai.azure.com/"
}
"####;
    let instance =
        RemoteConnection::from_json(json_data).expect("Failed to load RemoteConnection from JSON");
    assert_eq!(instance.kind, "remote");
    assert_eq!(instance.name, "my-reference-connection");
    assert_eq!(
        instance.endpoint,
        "https://{your-custom-endpoint}.openai.azure.com/"
    );
}

#[test]
fn test_remote_connection_load_yaml() {
    let yaml_data = r####"
kind: remote
name: my-reference-connection
endpoint: "https://{your-custom-endpoint}.openai.azure.com/"

"####;
    let instance =
        RemoteConnection::from_yaml(yaml_data).expect("Failed to load RemoteConnection from YAML");
    assert_eq!(instance.kind, "remote");
    assert_eq!(instance.name, "my-reference-connection");
    assert_eq!(
        instance.endpoint,
        "https://{your-custom-endpoint}.openai.azure.com/"
    );
}

#[test]
fn test_remote_connection_roundtrip() {
    let json_data = r####"
{
  "kind": "remote",
  "name": "my-reference-connection",
  "endpoint": "https://{your-custom-endpoint}.openai.azure.com/"
}
"####;
    let instance = RemoteConnection::from_json(json_data).expect("Failed to load RemoteConnection");
    let json_out = instance
        .to_json()
        .expect("Failed to serialize RemoteConnection to JSON");
    let reloaded = RemoteConnection::from_json(&json_out)
        .expect("Failed to reload RemoteConnection from JSON");
    assert_eq!(reloaded.kind, "remote");
    assert_eq!(reloaded.name, "my-reference-connection");
    assert_eq!(
        reloaded.endpoint,
        "https://{your-custom-endpoint}.openai.azure.com/"
    );
}

#[test]
fn test_remote_connection_to_json() {
    let json_data = r####"
{
  "kind": "remote",
  "name": "my-reference-connection",
  "endpoint": "https://{your-custom-endpoint}.openai.azure.com/"
}
"####;
    let instance = RemoteConnection::from_json(json_data).expect("Failed to load RemoteConnection");
    let json_out = instance
        .to_json()
        .expect("Failed to convert RemoteConnection to JSON");
    // Verify the output is valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_out).expect("Generated JSON is not valid");
}

#[test]
fn test_remote_connection_to_yaml() {
    let json_data = r####"
{
  "kind": "remote",
  "name": "my-reference-connection",
  "endpoint": "https://{your-custom-endpoint}.openai.azure.com/"
}
"####;
    let instance = RemoteConnection::from_json(json_data).expect("Failed to load RemoteConnection");
    let yaml_out = instance
        .to_yaml()
        .expect("Failed to convert RemoteConnection to YAML");
    // Verify the output is valid YAML by re-loading
    let _: serde_json::Value =
        serde_yaml::from_str(&yaml_out).expect("Generated YAML is not valid");
}
