// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_template_load_json() {
    let json_data = r####"
{
  "format": {
    "kind": "mustache"
  },
  "parser": {
    "kind": "mustache"
  }
}
"####;
    let instance = Template::from_json(json_data).expect("Failed to load Template from JSON");
    let _ = instance; // No scalar properties to validate
}

#[test]
fn test_template_load_yaml() {
    let yaml_data = r####"
format:
  kind: mustache
parser:
  kind: mustache

"####;
    let instance = Template::from_yaml(yaml_data).expect("Failed to load Template from YAML");
    let _ = instance;
}

#[test]
fn test_template_roundtrip() {
    let json_data = r####"
{
  "format": {
    "kind": "mustache"
  },
  "parser": {
    "kind": "mustache"
  }
}
"####;
    let instance = Template::from_json(json_data).expect("Failed to load Template");
    let json_out = instance
        .to_json()
        .expect("Failed to serialize Template to JSON");
    let reloaded = Template::from_json(&json_out).expect("Failed to reload Template from JSON");
    let _ = reloaded;
}

#[test]
fn test_template_to_json() {
    let json_data = r####"
{
  "format": {
    "kind": "mustache"
  },
  "parser": {
    "kind": "mustache"
  }
}
"####;
    let instance = Template::from_json(json_data).expect("Failed to load Template");
    let json_out = instance
        .to_json()
        .expect("Failed to convert Template to JSON");
    // Verify the output is valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_out).expect("Generated JSON is not valid");
}

#[test]
fn test_template_to_yaml() {
    let json_data = r####"
{
  "format": {
    "kind": "mustache"
  },
  "parser": {
    "kind": "mustache"
  }
}
"####;
    let instance = Template::from_json(json_data).expect("Failed to load Template");
    let yaml_out = instance
        .to_yaml()
        .expect("Failed to convert Template to YAML");
    // Verify the output is valid YAML by re-loading
    let _: serde_json::Value =
        serde_yaml::from_str(&yaml_out).expect("Generated YAML is not valid");
}
