// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::ToolboxTool;

#[test]
fn test_toolbox_tool_load_json() {
    let json = r####"
{
  "id": "web_search",
  "name": "my-search-tool",
  "description": "Searches the web for up-to-date information",
  "target": "https://api.githubcopilot.com/mcp",
  "authType": "OAuth2",
  "options": {
    "indexName": "products-index"
  }
}
"####;
    let result = ToolboxTool::from_json(json);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.id, "web_search");
    assert!(instance.name.is_some(), "Expected name to be Some");
    assert_eq!(instance.name.as_ref().unwrap(), &"my-search-tool");
    assert!(
        instance.description.is_some(),
        "Expected description to be Some"
    );
    assert_eq!(
        instance.description.as_ref().unwrap(),
        &"Searches the web for up-to-date information"
    );
    assert!(instance.target.is_some(), "Expected target to be Some");
    assert_eq!(
        instance.target.as_ref().unwrap(),
        &"https://api.githubcopilot.com/mcp"
    );
    assert!(
        instance.auth_type.is_some(),
        "Expected auth_type to be Some"
    );
    assert_eq!(instance.auth_type.as_ref().unwrap(), &"OAuth2");
}

#[test]
fn test_toolbox_tool_load_yaml() {
    let yaml = r####"
id: web_search
name: my-search-tool
description: Searches the web for up-to-date information
target: "https://api.githubcopilot.com/mcp"
authType: OAuth2
options:
  indexName: products-index

"####;
    let result = ToolboxTool::from_yaml(yaml);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.id, "web_search");
    assert!(instance.name.is_some(), "Expected name to be Some");
    assert!(
        instance.description.is_some(),
        "Expected description to be Some"
    );
    assert!(instance.target.is_some(), "Expected target to be Some");
    assert!(
        instance.auth_type.is_some(),
        "Expected auth_type to be Some"
    );
}

#[test]
fn test_toolbox_tool_roundtrip() {
    let json = r####"
{
  "id": "web_search",
  "name": "my-search-tool",
  "description": "Searches the web for up-to-date information",
  "target": "https://api.githubcopilot.com/mcp",
  "authType": "OAuth2",
  "options": {
    "indexName": "products-index"
  }
}
"####;
    let result = ToolboxTool::from_json(json);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let json_output = instance.to_json();
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}
