// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::*;

#[test]
fn test_tool_load_json() {
    let json_data = r####"
{
  "name": "my-tool",
  "kind": "function",
  "description": "A description of the tool",
  "bindings": {
    "input": "value"
  }
}
"####;
    let instance = Tool::from_json(json_data).expect("Failed to load Tool from JSON");
    // Polymorphic base type – use from_json_polymorphic for dispatch
    let _ = instance;
}

#[test]
fn test_tool_load_yaml() {
    let yaml_data = r####"
name: my-tool
kind: function
description: A description of the tool
bindings:
  input: value

"####;
    let instance = Tool::from_yaml(yaml_data).expect("Failed to load Tool from YAML");
    let _ = instance;
}

#[test]
fn test_tool_roundtrip() {
    let json_data = r####"
{
  "name": "my-tool",
  "kind": "function",
  "description": "A description of the tool",
  "bindings": {
    "input": "value"
  }
}
"####;
    let instance = Tool::from_json(json_data).expect("Failed to load Tool");
    let _ = instance;
}

#[test]
fn test_tool_to_json() {
    let json_data = r####"
{
  "name": "my-tool",
  "kind": "function",
  "description": "A description of the tool",
  "bindings": {
    "input": "value"
  }
}
"####;
    let instance = Tool::from_json(json_data).expect("Failed to load Tool");
    let _ = instance;
}

#[test]
fn test_tool_to_yaml() {
    let json_data = r####"
{
  "name": "my-tool",
  "kind": "function",
  "description": "A description of the tool",
  "bindings": {
    "input": "value"
  }
}
"####;
    let instance = Tool::from_json(json_data).expect("Failed to load Tool");
    let _ = instance;
}
