// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::ToolboxResource;

#[test]
fn test_toolbox_resource_load_json() {
    let json = r####"
{
  "kind": "toolbox",
  "description": "Shared platform tools",
  "tools": [
    {
      "id": "bing_grounding"
    },
    {
      "id": "azure_ai_search",
      "options": {
        "indexName": "products-index"
      }
    },
    {
      "id": "mcp",
      "name": "github-copilot",
      "target": "https://api.githubcopilot.com/mcp",
      "authType": "OAuth2"
    }
  ]
}
"####;
    let result = ToolboxResource::from_json(json);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.kind, "toolbox");
    assert!(
        instance.description.is_some(),
        "Expected description to be Some"
    );
    assert_eq!(
        instance.description.as_ref().unwrap(),
        &"Shared platform tools"
    );
}

#[test]
fn test_toolbox_resource_load_yaml() {
    let yaml = r####"
kind: toolbox
description: Shared platform tools
tools:
  - id: bing_grounding
  - id: azure_ai_search
    options:
      indexName: products-index
  - id: mcp
    name: github-copilot
    target: "https://api.githubcopilot.com/mcp"
    authType: OAuth2

"####;
    let result = ToolboxResource::from_yaml(yaml);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.kind, "toolbox");
    assert!(
        instance.description.is_some(),
        "Expected description to be Some"
    );
}

#[test]
fn test_toolbox_resource_roundtrip() {
    let json = r####"
{
  "kind": "toolbox",
  "description": "Shared platform tools",
  "tools": [
    {
      "id": "bing_grounding"
    },
    {
      "id": "azure_ai_search",
      "options": {
        "indexName": "products-index"
      }
    },
    {
      "id": "mcp",
      "name": "github-copilot",
      "target": "https://api.githubcopilot.com/mcp",
      "authType": "OAuth2"
    }
  ]
}
"####;
    let result = ToolboxResource::from_json(json);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let json_output = instance.to_json();
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}
