// Code generated by AgentSchema emitter; DO NOT EDIT.

use agentschema::Workflow;

#[test]
fn test_workflow_load_json() {
    let json = r####"
{
  "kind": "workflow"
}
"####;
    let result = Workflow::from_json(json);
    assert!(
        result.is_ok(),
        "Failed to load from JSON: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.kind, "workflow");
}

#[test]
fn test_workflow_load_yaml() {
    let yaml = r####"
kind: workflow

"####;
    let result = Workflow::from_yaml(yaml);
    assert!(
        result.is_ok(),
        "Failed to load from YAML: {:?}",
        result.err()
    );
    let instance = result.unwrap();
    assert_eq!(instance.kind, "workflow");
}

#[test]
fn test_workflow_roundtrip() {
    let json = r####"
{
  "kind": "workflow"
}
"####;
    let result = Workflow::from_json(json);
    assert!(result.is_ok(), "Failed to load: {:?}", result.err());
    let instance = result.unwrap();
    let json_output = instance.to_json();
    assert!(
        json_output.is_ok(),
        "Failed to serialize to JSON: {:?}",
        json_output.err()
    );
}
