// Code generated by AgentSchema emitter; DO NOT EDIT.

#[allow(unused_imports)]
use crate::*;

/// AgentDefinition represents The following is a specification for defining AI agents with structured metadata, inputs, outputs, tools, and templates.
/// It provides a way to create reusable and composable AI agents that can be executed with specific configurations.
/// The specification includes metadata about the agent, model configuration, input parameters, expected outputs,
/// available tools, and template configurations for prompt rendering.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct AgentDefinition {
    #[serde(rename = "kind", default)]
    pub kind: String,
    #[serde(rename = "name", default)]
    pub name: String,
    #[serde(
        rename = "displayName",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub display_name: Option<String>,
    #[serde(
        rename = "description",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub description: Option<String>,
    #[serde(rename = "metadata", default)]
    pub metadata: serde_json::Value,
    #[serde(
        rename = "inputSchema",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub input_schema: Option<PropertySchema>,
    #[serde(
        rename = "outputSchema",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub output_schema: Option<PropertySchema>,
}

impl AgentDefinition {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a JSON string, dispatching to the appropriate child type.
    /// Returns a `serde_json::Value` containing the deserialized child type.
    pub fn from_json_polymorphic(s: &str) -> Result<serde_json::Value, String> {
        let val: serde_json::Value = serde_json::from_str(s).map_err(|e| e.to_string())?;
        Self::load_polymorphic(val)
    }

    /// Load from a YAML string, dispatching to the appropriate child type.
    /// Returns a `serde_json::Value` containing the deserialized child type.
    pub fn from_yaml_polymorphic(s: &str) -> Result<serde_json::Value, String> {
        let val: serde_json::Value = serde_yaml::from_str(s).map_err(|e| e.to_string())?;
        Self::load_polymorphic(val)
    }

    /// Dispatch a `serde_json::Value` to the appropriate child type based on
    /// the `kind` discriminator field.
    pub fn load_polymorphic(val: serde_json::Value) -> Result<serde_json::Value, String> {
        if let Some(disc) = val.get("kind").and_then(|v| v.as_str()) {
            match disc {
                "prompt" => {
                    let typed = PromptAgent::from_json(
                        &serde_json::to_string(&val).map_err(|e| e.to_string())?,
                    )?;
                    serde_json::to_value(typed).map_err(|e| e.to_string())
                }
                "workflow" => {
                    let typed = Workflow::from_json(
                        &serde_json::to_string(&val).map_err(|e| e.to_string())?,
                    )?;
                    serde_json::to_value(typed).map_err(|e| e.to_string())
                }
                "hosted" => {
                    let typed = ContainerAgent::from_json(
                        &serde_json::to_string(&val).map_err(|e| e.to_string())?,
                    )?;
                    serde_json::to_value(typed).map_err(|e| e.to_string())
                }
                _ => serde_json::to_value(
                    serde_json::from_value::<AgentDefinition>(val).map_err(|e| e.to_string())?,
                )
                .map_err(|e| e.to_string()),
            }
        } else {
            Ok(val)
        }
    }
}

/// PromptAgent represents Prompt based agent definition. Used to create agents that can be executed directly.
/// These agents can leverage tools, input parameters, and templates to generate responses.
/// They are designed to be straightforward and easy to use for various applications.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct PromptAgent {
    #[serde(rename = "kind", default)]
    pub kind: String,
    #[serde(rename = "model", default)]
    pub model: Model,
    #[serde(rename = "tools", default)]
    pub tools: serde_json::Value,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none", default)]
    pub template: Option<Template>,
    #[serde(
        rename = "instructions",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub instructions: Option<String>,
    #[serde(
        rename = "additionalInstructions",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub additional_instructions: Option<String>,
}

impl PromptAgent {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }
}

/// Workflow represents A workflow agent that can orchestrate multiple steps and actions.
/// This agent type is designed to handle complex workflows that may involve
/// multiple tools, models, and decision points.
///
/// The workflow agent can be configured with a series of steps that define
/// the flow of execution, including conditional logic and parallel processing.
/// This allows for the creation of sophisticated AI-driven processes that can
/// adapt to various scenarios and requirements.
///
/// Note: The detailed structure of the workflow steps and actions is not defined here
/// and would need to be implemented based on specific use cases and requirements.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct Workflow {
    #[serde(rename = "kind", default)]
    pub kind: String,
    #[serde(rename = "trigger", default)]
    pub trigger: serde_json::Value,
}

impl Workflow {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }
}

/// ContainerAgent represents This represents a container based agent hosted by the provider/publisher.
/// The intent is to represent a container application that the user wants to run
/// in a hosted environment that the provider manages.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct ContainerAgent {
    #[serde(rename = "kind", default)]
    pub kind: String,
    #[serde(rename = "protocols", default)]
    pub protocols: serde_json::Value,
    #[serde(rename = "environmentVariables", default)]
    pub environment_variables: serde_json::Value,
}

impl ContainerAgent {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }
}
