

// Code generated by AgentSchema emitter; DO NOT EDIT.




/// Configuration for code-based (ZIP upload) deployment of a hosted agent. When present, the agent source code is uploaded directly instead of building a container image.
#[derive(Debug, Clone, Default)]
pub struct CodeConfiguration {
    /// Runtime identifier for code execution (e.g., 'python_3_11', 'dotnet_8').
    pub runtime: String,
    /// The entry point file for the agent (e.g., 'main.py' for Python, 'HelloWorld.dll' for .NET).
    pub entry_point: String,
    /// How package dependencies are resolved at deployment time.
    pub dependency_resolution: Option<String>,
}

impl CodeConfiguration {
    /// Create a new CodeConfiguration with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load CodeConfiguration from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load CodeConfiguration from a YAML string.
    pub fn from_yaml(yaml: &str) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load CodeConfiguration from a `serde_json::Value`.
    pub fn load_from_value(value: &serde_json::Value) -> Self {
        Self {
            runtime: value.get("runtime").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            entry_point: value.get("entryPoint").and_then(|v| v.as_str()).unwrap_or_default().to_string(),
            dependency_resolution: value.get("dependencyResolution").and_then(|v| v.as_str()).map(|s| s.to_string()),
        }
    }

    /// Serialize CodeConfiguration to a `serde_json::Value`.
    pub fn to_value(&self) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        if !self.runtime.is_empty() {
            result.insert("runtime".to_string(), serde_json::Value::String(self.runtime.clone()));
        }
        if !self.entry_point.is_empty() {
            result.insert("entryPoint".to_string(), serde_json::Value::String(self.entry_point.clone()));
        }
        if let Some(ref val) = self.dependency_resolution {
            result.insert("dependencyResolution".to_string(), serde_json::Value::String(val.clone()));
        }
        serde_json::Value::Object(result)
    }

    /// Serialize CodeConfiguration to a JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value())
    }

    /// Serialize CodeConfiguration to a YAML string.
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value())
    }
}


