// Code generated by AgentSchema emitter; DO NOT EDIT.

/// Definition for an environment variable used in containerized agents.
#[derive(Debug, Clone)]
pub struct EnvironmentVariable {
    /// Name of the environment variable
    pub name: String,
    /// Environment variable resolution
    pub value: String,
}

impl Default for EnvironmentVariable {
    fn default() -> Self {
        EnvironmentVariable {
            name: String::from(""),
            value: String::from(""),
        }
    }
}

impl EnvironmentVariable {
    /// Create a new EnvironmentVariable with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load EnvironmentVariable from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load EnvironmentVariable from a YAML string.
    pub fn from_yaml(yaml: &str) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load EnvironmentVariable from a `serde_json::Value`.
    pub fn load_from_value(value: &serde_json::Value) -> Self {
        let mut result = Self::default();
        // Load fields from JSON object
        result.name = value
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string();
        result.value = value
            .get("value")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string();
        result
    }

    /// Serialize EnvironmentVariable to a `serde_json::Value`.
    pub fn to_value(&self) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        if !self.name.is_empty() {
            result.insert(
                "name".to_string(),
                serde_json::Value::String(self.name.clone()),
            );
        }
        if !self.value.is_empty() {
            result.insert(
                "value".to_string(),
                serde_json::Value::String(self.value.clone()),
            );
        }
        serde_json::Value::Object(result)
    }

    /// Serialize EnvironmentVariable to a JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value())
    }

    /// Serialize EnvironmentVariable to a YAML string.
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value())
    }
}
