// Code generated by AgentSchema emitter; DO NOT EDIT.

#[allow(unused_imports)]
use crate::*;

#[doc(hidden)]
#[derive(serde::Deserialize)]
struct _FormatFields {
    #[serde(rename = "kind", default)]
    kind: String,
    #[serde(rename = "strict", default)]
    strict: Option<bool>,
    #[serde(rename = "options", default)]
    options: serde_json::Value,
}

#[doc(hidden)]
#[derive(serde::Deserialize)]
#[serde(untagged)]
enum _FormatRepr {
    Short(String),
    Full(_FormatFields),
}

/// Format represents Template format definition

#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct Format {
    #[serde(rename = "kind", default)]
    pub kind: String,
    #[serde(rename = "strict", skip_serializing_if = "Option::is_none", default)]
    pub strict: Option<bool>,
    #[serde(rename = "options", default)]
    pub options: serde_json::Value,
}

impl<'de> serde::Deserialize<'de> for Format {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let repr = _FormatRepr::deserialize(d)?;
        match repr {
            _FormatRepr::Short(v) => {
                let expanded = serde_json::json!({
                    "kind": v
                });
                let fields: _FormatFields = serde_json::from_value(expanded)
                    .map_err(|e| serde::de::Error::custom(e.to_string()))?;
                Ok(Format {
                    kind: fields.kind,
                    strict: fields.strict,
                    options: fields.options,
                })
            }
            _FormatRepr::Full(f) => Ok(Format {
                kind: f.kind,
                strict: f.strict,
                options: f.options,
            }),
        }
    }
}

impl Format {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }
}
