// Code generated by AgentSchema emitter; DO NOT EDIT.

/// The approval mode for MCP server tools.
#[derive(Debug, Clone)]
pub struct McpServerApprovalMode {
    /// The kind identifier for string approval modes
    pub kind: String,
}

impl Default for McpServerApprovalMode {
    fn default() -> Self {
        McpServerApprovalMode {
            kind: String::from(""),
        }
    }
}

impl McpServerApprovalMode {
    /// Create a new McpServerApprovalMode with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load McpServerApprovalMode from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load McpServerApprovalMode from a YAML string.
    pub fn from_yaml(yaml: &str) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load McpServerApprovalMode from a `serde_json::Value`.
    pub fn load_from_value(value: &serde_json::Value) -> Self {
        let mut result = Self::default();
        if let Some(s) = value.as_str() {
            let value = s.to_string();
            let expansion = serde_json::json!({"kind":value});
            return Self::load_from_value(&expansion);
        }
        // Load fields from JSON object
        result.kind = value
            .get("kind")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string();
        result
    }

    /// Serialize McpServerApprovalMode to a `serde_json::Value`.
    pub fn to_value(&self) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        if !self.kind.is_empty() {
            result.insert(
                "kind".to_string(),
                serde_json::Value::String(self.kind.clone()),
            );
        }
        serde_json::Value::Object(result)
    }

    /// Serialize McpServerApprovalMode to a JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value())
    }

    /// Serialize McpServerApprovalMode to a YAML string.
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value())
    }
}

/// McpServerToolAlwaysRequireApprovalMode schema type
#[derive(Debug, Clone)]
pub struct McpServerToolAlwaysRequireApprovalMode {
    /// The kind identifier for always approval mode
    pub kind: String,
}

impl Default for McpServerToolAlwaysRequireApprovalMode {
    fn default() -> Self {
        McpServerToolAlwaysRequireApprovalMode {
            kind: String::from("always"),
        }
    }
}

impl McpServerToolAlwaysRequireApprovalMode {
    /// Create a new McpServerToolAlwaysRequireApprovalMode with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load McpServerToolAlwaysRequireApprovalMode from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load McpServerToolAlwaysRequireApprovalMode from a YAML string.
    pub fn from_yaml(yaml: &str) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load McpServerToolAlwaysRequireApprovalMode from a `serde_json::Value`.
    pub fn load_from_value(value: &serde_json::Value) -> Self {
        let mut result = Self::default();
        // Load fields from JSON object
        result.kind = value
            .get("kind")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string();
        result
    }

    /// Serialize McpServerToolAlwaysRequireApprovalMode to a `serde_json::Value`.
    pub fn to_value(&self) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        if !self.kind.is_empty() {
            result.insert(
                "kind".to_string(),
                serde_json::Value::String(self.kind.clone()),
            );
        }
        serde_json::Value::Object(result)
    }

    /// Serialize McpServerToolAlwaysRequireApprovalMode to a JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value())
    }

    /// Serialize McpServerToolAlwaysRequireApprovalMode to a YAML string.
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value())
    }
}

/// McpServerToolNeverRequireApprovalMode schema type
#[derive(Debug, Clone)]
pub struct McpServerToolNeverRequireApprovalMode {
    /// The kind identifier for never approval mode
    pub kind: String,
}

impl Default for McpServerToolNeverRequireApprovalMode {
    fn default() -> Self {
        McpServerToolNeverRequireApprovalMode {
            kind: String::from("never"),
        }
    }
}

impl McpServerToolNeverRequireApprovalMode {
    /// Create a new McpServerToolNeverRequireApprovalMode with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load McpServerToolNeverRequireApprovalMode from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load McpServerToolNeverRequireApprovalMode from a YAML string.
    pub fn from_yaml(yaml: &str) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load McpServerToolNeverRequireApprovalMode from a `serde_json::Value`.
    pub fn load_from_value(value: &serde_json::Value) -> Self {
        let mut result = Self::default();
        // Load fields from JSON object
        result.kind = value
            .get("kind")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string();
        result
    }

    /// Serialize McpServerToolNeverRequireApprovalMode to a `serde_json::Value`.
    pub fn to_value(&self) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        if !self.kind.is_empty() {
            result.insert(
                "kind".to_string(),
                serde_json::Value::String(self.kind.clone()),
            );
        }
        serde_json::Value::Object(result)
    }

    /// Serialize McpServerToolNeverRequireApprovalMode to a JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value())
    }

    /// Serialize McpServerToolNeverRequireApprovalMode to a YAML string.
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value())
    }
}

/// McpServerToolSpecifyApprovalMode schema type
#[derive(Debug, Clone)]
pub struct McpServerToolSpecifyApprovalMode {
    /// The kind identifier for specify approval mode
    pub kind: String,
    /// List of tools that always require approval
    pub always_require_approval_tools: Vec<String>,
    /// List of tools that never require approval
    pub never_require_approval_tools: Vec<String>,
}

impl Default for McpServerToolSpecifyApprovalMode {
    fn default() -> Self {
        McpServerToolSpecifyApprovalMode {
            kind: String::from("specify"),
            always_require_approval_tools: Vec::new(),
            never_require_approval_tools: Vec::new(),
        }
    }
}

impl McpServerToolSpecifyApprovalMode {
    /// Create a new McpServerToolSpecifyApprovalMode with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load McpServerToolSpecifyApprovalMode from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load McpServerToolSpecifyApprovalMode from a YAML string.
    pub fn from_yaml(yaml: &str) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load McpServerToolSpecifyApprovalMode from a `serde_json::Value`.
    pub fn load_from_value(value: &serde_json::Value) -> Self {
        let mut result = Self::default();
        // Load fields from JSON object
        result.kind = value
            .get("kind")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string();
        if let Some(arr) = value
            .get("alwaysRequireApprovalTools")
            .and_then(|v| v.as_array())
        {
            result.always_require_approval_tools = arr
                .iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect();
        }
        if let Some(arr) = value
            .get("neverRequireApprovalTools")
            .and_then(|v| v.as_array())
        {
            result.never_require_approval_tools = arr
                .iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect();
        }
        result
    }

    /// Serialize McpServerToolSpecifyApprovalMode to a `serde_json::Value`.
    pub fn to_value(&self) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        if !self.kind.is_empty() {
            result.insert(
                "kind".to_string(),
                serde_json::Value::String(self.kind.clone()),
            );
        }
        if !self.always_require_approval_tools.is_empty() {
            result.insert(
                "alwaysRequireApprovalTools".to_string(),
                serde_json::to_value(&self.always_require_approval_tools)
                    .unwrap_or(serde_json::Value::Null),
            );
        }
        if !self.never_require_approval_tools.is_empty() {
            result.insert(
                "neverRequireApprovalTools".to_string(),
                serde_json::to_value(&self.never_require_approval_tools)
                    .unwrap_or(serde_json::Value::Null),
            );
        }
        serde_json::Value::Object(result)
    }

    /// Serialize McpServerToolSpecifyApprovalMode to a JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value())
    }

    /// Serialize McpServerToolSpecifyApprovalMode to a YAML string.
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value())
    }
}
