// Code generated by AgentSchema emitter; DO NOT EDIT.

#[allow(unused_imports)]
use crate::*;

#[doc(hidden)]
#[derive(serde::Deserialize)]
struct _ModelFields {
    #[serde(rename = "id", default)]
    id: String,
    #[serde(rename = "provider", default)]
    provider: Option<String>,
    #[serde(rename = "apiType", default)]
    api_type: Option<String>,
    #[serde(rename = "connection", default)]
    connection: Option<serde_json::Value>,
    #[serde(rename = "options", default)]
    options: Option<ModelOptions>,
}

#[doc(hidden)]
#[derive(serde::Deserialize)]
#[serde(untagged)]
enum _ModelRepr {
    Short(String),
    Full(_ModelFields),
}

/// Model represents Model for defining the structure and behavior of AI agents.
/// This model includes properties for specifying the model's provider, connection details, and various options.
/// It allows for flexible configuration of AI models to suit different use cases and requirements.

#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct Model {
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none", default)]
    pub provider: Option<String>,
    #[serde(rename = "apiType", skip_serializing_if = "Option::is_none", default)]
    pub api_type: Option<String>,
    #[serde(
        rename = "connection",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub connection: Option<serde_json::Value>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none", default)]
    pub options: Option<ModelOptions>,
}

impl<'de> serde::Deserialize<'de> for Model {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let repr = _ModelRepr::deserialize(d)?;
        match repr {
            _ModelRepr::Short(v) => {
                let expanded = serde_json::json!({
                    "id": v
                });
                let fields: _ModelFields = serde_json::from_value(expanded)
                    .map_err(|e| serde::de::Error::custom(e.to_string()))?;
                Ok(Model {
                    id: fields.id,
                    provider: fields.provider,
                    api_type: fields.api_type,
                    connection: fields.connection,
                    options: fields.options,
                })
            }
            _ModelRepr::Full(f) => Ok(Model {
                id: f.id,
                provider: f.provider,
                api_type: f.api_type,
                connection: f.connection,
                options: f.options,
            }),
        }
    }
}

impl Model {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }
}
