// Code generated by AgentSchema emitter; DO NOT EDIT.

#[allow(unused_imports)]
use crate::*;

/// PropertySchema represents Definition for the property schema of a model.
/// This includes the properties and example records.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct PropertySchema {
    #[serde(rename = "examples", default)]
    pub examples: serde_json::Value,
    #[serde(rename = "strict", skip_serializing_if = "Option::is_none", default)]
    pub strict: Option<bool>,
    #[serde(rename = "properties", default)]
    pub properties: serde_json::Value,
}

impl PropertySchema {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }
}
