// Code generated by AgentSchema emitter; DO NOT EDIT.

#[allow(unused_imports)]
use crate::*;

/// Resource represents Represents a resource required by the agent
/// Resources can include databases, APIs, or other external systems
/// that the agent needs to interact with to perform its tasks

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct Resource {
    #[serde(rename = "name", default)]
    pub name: String,
    #[serde(rename = "kind", default)]
    pub kind: String,
}

impl Resource {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a JSON string, dispatching to the appropriate child type.
    /// Returns a `serde_json::Value` containing the deserialized child type.
    pub fn from_json_polymorphic(s: &str) -> Result<serde_json::Value, String> {
        let val: serde_json::Value = serde_json::from_str(s).map_err(|e| e.to_string())?;
        Self::load_polymorphic(val)
    }

    /// Load from a YAML string, dispatching to the appropriate child type.
    /// Returns a `serde_json::Value` containing the deserialized child type.
    pub fn from_yaml_polymorphic(s: &str) -> Result<serde_json::Value, String> {
        let val: serde_json::Value = serde_yaml::from_str(s).map_err(|e| e.to_string())?;
        Self::load_polymorphic(val)
    }

    /// Dispatch a `serde_json::Value` to the appropriate child type based on
    /// the `kind` discriminator field.
    pub fn load_polymorphic(val: serde_json::Value) -> Result<serde_json::Value, String> {
        if let Some(disc) = val.get("kind").and_then(|v| v.as_str()) {
            match disc {
                "model" => {
                    let typed = ModelResource::from_json(
                        &serde_json::to_string(&val).map_err(|e| e.to_string())?,
                    )?;
                    serde_json::to_value(typed).map_err(|e| e.to_string())
                }
                "tool" => {
                    let typed = ToolResource::from_json(
                        &serde_json::to_string(&val).map_err(|e| e.to_string())?,
                    )?;
                    serde_json::to_value(typed).map_err(|e| e.to_string())
                }
                _ => serde_json::to_value(
                    serde_json::from_value::<Resource>(val).map_err(|e| e.to_string())?,
                )
                .map_err(|e| e.to_string()),
            }
        } else {
            Ok(val)
        }
    }
}

/// ModelResource represents Represents a model resource required by the agent

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct ModelResource {
    #[serde(rename = "kind", default)]
    pub kind: String,
    #[serde(rename = "id", default)]
    pub id: String,
}

impl ModelResource {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }
}

/// ToolResource represents Represents a tool resource required by the agent

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct ToolResource {
    #[serde(rename = "kind", default)]
    pub kind: String,
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "options", default)]
    pub options: serde_json::Value,
}

impl ToolResource {
    /// Load from a JSON string.
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string(self).map_err(|e| e.to_string())
    }

    /// Load from a YAML string.
    pub fn from_yaml(s: &str) -> Result<Self, String> {
        serde_yaml::from_str(s).map_err(|e| e.to_string())
    }

    /// Serialize to a YAML string.
    pub fn to_yaml(&self) -> Result<String, String> {
        serde_yaml::to_string(self).map_err(|e| e.to_string())
    }
}
