// Code generated by AgentSchema emitter; DO NOT EDIT.

/// Represents a tool definition within a toolbox. Tools can be Foundry-hosted (web_search, azure_ai_search, etc.) or external (mcp, openapi, a2a_preview) with connection details.
#[derive(Debug, Clone, Default)]
pub struct ToolboxTool {
    /// The tool type identifier (e.g., 'web_search', 'azure_ai_search', 'mcp', 'a2a_preview')
    pub id: String,
    /// Optional display name for the tool
    pub name: Option<String>,
    /// Human-readable description of the tool's capabilities
    pub description: Option<String>,
    /// Target endpoint URL for external tools (e.g., MCP server URL, A2A agent URL)
    pub target: Option<String>,
    /// Authentication type for the tool connection
    pub auth_type: Option<String>,
    /// Additional configuration options for the tool
    pub options: serde_json::Value,
}

impl ToolboxTool {
    /// Create a new ToolboxTool with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load ToolboxTool from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load ToolboxTool from a YAML string.
    pub fn from_yaml(yaml: &str) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Ok(Self::load_from_value(&value))
    }

    /// Load ToolboxTool from a `serde_json::Value`.
    pub fn load_from_value(value: &serde_json::Value) -> Self {
        Self {
            id: value
                .get("id")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
            name: value
                .get("name")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            description: value
                .get("description")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            target: value
                .get("target")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            auth_type: value
                .get("authType")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            options: value
                .get("options")
                .cloned()
                .unwrap_or(serde_json::Value::Null),
        }
    }

    /// Serialize ToolboxTool to a `serde_json::Value`.
    pub fn to_value(&self) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        if !self.id.is_empty() {
            result.insert("id".to_string(), serde_json::Value::String(self.id.clone()));
        }
        if let Some(ref val) = self.name {
            result.insert("name".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(ref val) = self.description {
            result.insert(
                "description".to_string(),
                serde_json::Value::String(val.clone()),
            );
        }
        if let Some(ref val) = self.target {
            result.insert("target".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(ref val) = self.auth_type {
            result.insert(
                "authType".to_string(),
                serde_json::Value::String(val.clone()),
            );
        }
        if !self.options.is_null() {
            result.insert("options".to_string(), self.options.clone());
        }
        serde_json::Value::Object(result)
    }

    /// Serialize ToolboxTool to a JSON string.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value())
    }

    /// Serialize ToolboxTool to a YAML string.
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value())
    }
    /// Returns typed reference to the map if the field is an object.
    /// Returns `None` if the field is null or not an object.
    pub fn as_options_dict(&self) -> Option<&serde_json::Map<String, serde_json::Value>> {
        self.options.as_object()
    }
}
