
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class BindingTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
name: my-tool
input: input-variable

""";

        var instance = Binding.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("my-tool", instance.Name);
        Assert.Equal("input-variable", instance.Input);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "name": "my-tool",
  "input": "input-variable"
}
""";

        var instance = Binding.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("my-tool", instance.Name);
        Assert.Equal("input-variable", instance.Input);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "name": "my-tool",
  "input": "input-variable"
}
""";

        var instance = Binding.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = Binding.FromJson(json);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Name, reloaded.Name);
        Assert.Equal(instance.Input, reloaded.Input);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
name: my-tool
input: input-variable

""";

        var instance = Binding.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = Binding.FromYaml(yaml);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Name, reloaded.Name);
        Assert.Equal(instance.Input, reloaded.Input);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "name": "my-tool",
  "input": "input-variable"
}
""";

        var instance = Binding.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = Binding.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
name: my-tool
input: input-variable

""";

        var instance = Binding.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = Binding.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }
    [Fact]
    public void LoadJsonFromString()
    {
        // alternate representation as string
        var data = "\"example\"";
        var instance = Binding.FromJson(data);
        Assert.NotNull(instance);
        Assert.Equal("example", instance.Input);
    }


    [Fact]
    public void LoadYamlFromString()
    {
        // alternate representation as string
        var data = "\"example\"";
        var instance = Binding.FromYaml(data);
        Assert.NotNull(instance);
        Assert.Equal("example", instance.Input);
    }
    

    [Fact]
    public void LoadFromDictionary()
    {
        var data = new Dictionary<string, object?>();
        var instance = Binding.Load(data);
        Assert.NotNull(instance);
    }

    [Fact]
    public void SaveToDictionary()
    {
        var instance = new Binding();
        var data = instance.Save();
        Assert.NotNull(data);
        Assert.IsType<Dictionary<string, object?>>(data);
    }

}