
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class ConnectionTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
kind: reference
authenticationMode: system
usageDescription: This will allow the agent to respond to an email on your behalf

""";

        var instance = Connection.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("reference", instance.Kind);
        Assert.Equal("system", instance.AuthenticationMode);
        Assert.Equal("This will allow the agent to respond to an email on your behalf", instance.UsageDescription);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "kind": "reference",
  "authenticationMode": "system",
  "usageDescription": "This will allow the agent to respond to an email on your behalf"
}
""";

        var instance = Connection.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("reference", instance.Kind);
        Assert.Equal("system", instance.AuthenticationMode);
        Assert.Equal("This will allow the agent to respond to an email on your behalf", instance.UsageDescription);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "kind": "reference",
  "authenticationMode": "system",
  "usageDescription": "This will allow the agent to respond to an email on your behalf"
}
""";

        var instance = Connection.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = Connection.FromJson(json);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Kind, reloaded.Kind);
        Assert.Equal(instance.AuthenticationMode, reloaded.AuthenticationMode);
        Assert.Equal(instance.UsageDescription, reloaded.UsageDescription);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
kind: reference
authenticationMode: system
usageDescription: This will allow the agent to respond to an email on your behalf

""";

        var instance = Connection.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = Connection.FromYaml(yaml);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Kind, reloaded.Kind);
        Assert.Equal(instance.AuthenticationMode, reloaded.AuthenticationMode);
        Assert.Equal(instance.UsageDescription, reloaded.UsageDescription);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "kind": "reference",
  "authenticationMode": "system",
  "usageDescription": "This will allow the agent to respond to an email on your behalf"
}
""";

        var instance = Connection.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = Connection.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
kind: reference
authenticationMode: system
usageDescription: This will allow the agent to respond to an email on your behalf

""";

        var instance = Connection.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = Connection.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }

}