
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class ContainerAgentTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
kind: hosted
protocols:
  - protocol: responses
    version: v0.1.1
environmentVariables:
  - name: MY_ENV_VAR
    value: my-value

""";

        var instance = ContainerAgent.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("hosted", instance.Kind);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
""";

        var instance = ContainerAgent.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("hosted", instance.Kind);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
""";

        var instance = ContainerAgent.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = ContainerAgent.FromJson(json);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Kind, reloaded.Kind);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
kind: hosted
protocols:
  - protocol: responses
    version: v0.1.1
environmentVariables:
  - name: MY_ENV_VAR
    value: my-value

""";

        var instance = ContainerAgent.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = ContainerAgent.FromYaml(yaml);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Kind, reloaded.Kind);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "kind": "hosted",
  "protocols": [
    {
      "protocol": "responses",
      "version": "v0.1.1"
    }
  ],
  "environmentVariables": [
    {
      "name": "MY_ENV_VAR",
      "value": "my-value"
    }
  ]
}
""";

        var instance = ContainerAgent.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = ContainerAgent.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
kind: hosted
protocols:
  - protocol: responses
    version: v0.1.1
environmentVariables:
  - name: MY_ENV_VAR
    value: my-value

""";

        var instance = ContainerAgent.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = ContainerAgent.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void LoadFromDictionary()
    {
        var data = new Dictionary<string, object?>();
        var instance = ContainerAgent.Load(data);
        Assert.NotNull(instance);
    }

    [Fact]
    public void SaveToDictionary()
    {
        var instance = new ContainerAgent();
        var data = instance.Save();
        Assert.NotNull(data);
        Assert.IsType<Dictionary<string, object?>>(data);
    }

}