
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class CustomToolTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
connection:
  kind: reference
options:
  timeout: 30
  retries: 3

""";

        var instance = CustomTool.FromYaml(yamlData);

        Assert.NotNull(instance);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "connection": {
    "kind": "reference"
  },
  "options": {
    "timeout": 30,
    "retries": 3
  }
}
""";

        var instance = CustomTool.FromJson(jsonData);
        Assert.NotNull(instance);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "connection": {
    "kind": "reference"
  },
  "options": {
    "timeout": 30,
    "retries": 3
  }
}
""";

        var instance = CustomTool.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = CustomTool.FromJson(json);

        Assert.NotNull(reloaded);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
connection:
  kind: reference
options:
  timeout: 30
  retries: 3

""";

        var instance = CustomTool.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = CustomTool.FromYaml(yaml);

        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "connection": {
    "kind": "reference"
  },
  "options": {
    "timeout": 30,
    "retries": 3
  }
}
""";

        var instance = CustomTool.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = CustomTool.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
connection:
  kind: reference
options:
  timeout: 30
  retries: 3

""";

        var instance = CustomTool.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = CustomTool.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void LoadFromDictionary()
    {
        var data = new Dictionary<string, object?>();
        var instance = CustomTool.Load(data);
        Assert.NotNull(instance);
    }

    [Fact]
    public void SaveToDictionary()
    {
        var instance = new CustomTool();
        var data = instance.Save();
        Assert.NotNull(data);
        Assert.IsType<Dictionary<string, object?>>(data);
    }

}