
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class EnvironmentVariableTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
name: MY_ENV_VAR
value: my-value

""";

        var instance = EnvironmentVariable.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("MY_ENV_VAR", instance.Name);
        Assert.Equal("my-value", instance.Value);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "name": "MY_ENV_VAR",
  "value": "my-value"
}
""";

        var instance = EnvironmentVariable.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("MY_ENV_VAR", instance.Name);
        Assert.Equal("my-value", instance.Value);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "name": "MY_ENV_VAR",
  "value": "my-value"
}
""";

        var instance = EnvironmentVariable.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = EnvironmentVariable.FromJson(json);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Name, reloaded.Name);
        Assert.Equal(instance.Value, reloaded.Value);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
name: MY_ENV_VAR
value: my-value

""";

        var instance = EnvironmentVariable.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = EnvironmentVariable.FromYaml(yaml);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Name, reloaded.Name);
        Assert.Equal(instance.Value, reloaded.Value);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "name": "MY_ENV_VAR",
  "value": "my-value"
}
""";

        var instance = EnvironmentVariable.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = EnvironmentVariable.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
name: MY_ENV_VAR
value: my-value

""";

        var instance = EnvironmentVariable.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = EnvironmentVariable.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void LoadFromDictionary()
    {
        var data = new Dictionary<string, object?>();
        var instance = EnvironmentVariable.Load(data);
        Assert.NotNull(instance);
    }

    [Fact]
    public void SaveToDictionary()
    {
        var instance = new EnvironmentVariable();
        var data = instance.Save();
        Assert.NotNull(data);
        Assert.IsType<Dictionary<string, object?>>(data);
    }

}