
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class FormatTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
kind: mustache
strict: true
options:
  key: value

""";

        var instance = Format.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("mustache", instance.Kind);
        Assert.True(instance.Strict);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
""";

        var instance = Format.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("mustache", instance.Kind);
        Assert.True(instance.Strict);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
""";

        var instance = Format.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = Format.FromJson(json);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Kind, reloaded.Kind);
        Assert.True(reloaded.Strict);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
kind: mustache
strict: true
options:
  key: value

""";

        var instance = Format.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = Format.FromYaml(yaml);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Kind, reloaded.Kind);
        Assert.True(reloaded.Strict);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "kind": "mustache",
  "strict": true,
  "options": {
    "key": "value"
  }
}
""";

        var instance = Format.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = Format.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
kind: mustache
strict: true
options:
  key: value

""";

        var instance = Format.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = Format.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }
    [Fact]
    public void LoadJsonFromString()
    {
        // alternate representation as string
        var data = "\"example\"";
        var instance = Format.FromJson(data);
        Assert.NotNull(instance);
        Assert.Equal("example", instance.Kind);
    }


    [Fact]
    public void LoadYamlFromString()
    {
        // alternate representation as string
        var data = "\"example\"";
        var instance = Format.FromYaml(data);
        Assert.NotNull(instance);
        Assert.Equal("example", instance.Kind);
    }
    

}