
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class ModelTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
id: gpt-35-turbo
provider: azure
apiType: chat
connection:
  kind: key
  endpoint: "https://{your-custom-endpoint}.openai.azure.com/"
  key: "{your-api-key}"
options:
  type: chat
  temperature: 0.7
  maxTokens: 1000

""";

        var instance = Model.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("gpt-35-turbo", instance.Id);
        Assert.Equal("azure", instance.Provider);
        Assert.Equal("chat", instance.ApiType);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "id": "gpt-35-turbo",
  "provider": "azure",
  "apiType": "chat",
  "connection": {
    "kind": "key",
    "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
    "key": "{your-api-key}"
  },
  "options": {
    "type": "chat",
    "temperature": 0.7,
    "maxTokens": 1000
  }
}
""";

        var instance = Model.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("gpt-35-turbo", instance.Id);
        Assert.Equal("azure", instance.Provider);
        Assert.Equal("chat", instance.ApiType);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "id": "gpt-35-turbo",
  "provider": "azure",
  "apiType": "chat",
  "connection": {
    "kind": "key",
    "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
    "key": "{your-api-key}"
  },
  "options": {
    "type": "chat",
    "temperature": 0.7,
    "maxTokens": 1000
  }
}
""";

        var instance = Model.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = Model.FromJson(json);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Id, reloaded.Id);
        Assert.Equal(instance.Provider, reloaded.Provider);
        Assert.Equal(instance.ApiType, reloaded.ApiType);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
id: gpt-35-turbo
provider: azure
apiType: chat
connection:
  kind: key
  endpoint: "https://{your-custom-endpoint}.openai.azure.com/"
  key: "{your-api-key}"
options:
  type: chat
  temperature: 0.7
  maxTokens: 1000

""";

        var instance = Model.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = Model.FromYaml(yaml);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Id, reloaded.Id);
        Assert.Equal(instance.Provider, reloaded.Provider);
        Assert.Equal(instance.ApiType, reloaded.ApiType);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "id": "gpt-35-turbo",
  "provider": "azure",
  "apiType": "chat",
  "connection": {
    "kind": "key",
    "endpoint": "https://{your-custom-endpoint}.openai.azure.com/",
    "key": "{your-api-key}"
  },
  "options": {
    "type": "chat",
    "temperature": 0.7,
    "maxTokens": 1000
  }
}
""";

        var instance = Model.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = Model.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
id: gpt-35-turbo
provider: azure
apiType: chat
connection:
  kind: key
  endpoint: "https://{your-custom-endpoint}.openai.azure.com/"
  key: "{your-api-key}"
options:
  type: chat
  temperature: 0.7
  maxTokens: 1000

""";

        var instance = Model.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = Model.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }
    [Fact]
    public void LoadJsonFromString()
    {
        // alternate representation as string
        var data = "\"example\"";
        var instance = Model.FromJson(data);
        Assert.NotNull(instance);
        Assert.Equal("example", instance.Id);
    }


    [Fact]
    public void LoadYamlFromString()
    {
        // alternate representation as string
        var data = "\"example\"";
        var instance = Model.FromYaml(data);
        Assert.NotNull(instance);
        Assert.Equal("example", instance.Id);
    }
    

    [Fact]
    public void LoadFromDictionary()
    {
        var data = new Dictionary<string, object?>();
        var instance = Model.Load(data);
        Assert.NotNull(instance);
    }

    [Fact]
    public void SaveToDictionary()
    {
        var instance = new Model();
        var data = instance.Save();
        Assert.NotNull(data);
        Assert.IsType<Dictionary<string, object?>>(data);
    }

}