
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class ObjectPropertyTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
properties:
  property1:
    kind: string
  property2:
    kind: number

""";

        var instance = ObjectProperty.FromYaml(yamlData);

        Assert.NotNull(instance);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "properties": {
    "property1": {
      "kind": "string"
    },
    "property2": {
      "kind": "number"
    }
  }
}
""";

        var instance = ObjectProperty.FromJson(jsonData);
        Assert.NotNull(instance);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "properties": {
    "property1": {
      "kind": "string"
    },
    "property2": {
      "kind": "number"
    }
  }
}
""";

        var instance = ObjectProperty.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = ObjectProperty.FromJson(json);

        Assert.NotNull(reloaded);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
properties:
  property1:
    kind: string
  property2:
    kind: number

""";

        var instance = ObjectProperty.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = ObjectProperty.FromYaml(yaml);

        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "properties": {
    "property1": {
      "kind": "string"
    },
    "property2": {
      "kind": "number"
    }
  }
}
""";

        var instance = ObjectProperty.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = ObjectProperty.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
properties:
  property1:
    kind: string
  property2:
    kind: number

""";

        var instance = ObjectProperty.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = ObjectProperty.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void LoadFromDictionary()
    {
        var data = new Dictionary<string, object?>();
        var instance = ObjectProperty.Load(data);
        Assert.NotNull(instance);
    }

    [Fact]
    public void SaveToDictionary()
    {
        var instance = new ObjectProperty();
        var data = instance.Save();
        Assert.NotNull(data);
        Assert.IsType<Dictionary<string, object?>>(data);
    }

}