
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class PropertySchemaTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
examples:
  - key: value
strict: true
properties:
  firstName:
    kind: string
    sample: Jane
  lastName:
    kind: string
    sample: Doe
  question:
    kind: string
    sample: What is the meaning of life?

""";

        var instance = PropertySchema.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.True(instance.Strict);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "examples": [
    {
      "key": "value"
    }
  ],
  "strict": true,
  "properties": {
    "firstName": {
      "kind": "string",
      "sample": "Jane"
    },
    "lastName": {
      "kind": "string",
      "sample": "Doe"
    },
    "question": {
      "kind": "string",
      "sample": "What is the meaning of life?"
    }
  }
}
""";

        var instance = PropertySchema.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.True(instance.Strict);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "examples": [
    {
      "key": "value"
    }
  ],
  "strict": true,
  "properties": {
    "firstName": {
      "kind": "string",
      "sample": "Jane"
    },
    "lastName": {
      "kind": "string",
      "sample": "Doe"
    },
    "question": {
      "kind": "string",
      "sample": "What is the meaning of life?"
    }
  }
}
""";

        var instance = PropertySchema.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = PropertySchema.FromJson(json);

        Assert.NotNull(reloaded);
        Assert.True(reloaded.Strict);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
examples:
  - key: value
strict: true
properties:
  firstName:
    kind: string
    sample: Jane
  lastName:
    kind: string
    sample: Doe
  question:
    kind: string
    sample: What is the meaning of life?

""";

        var instance = PropertySchema.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = PropertySchema.FromYaml(yaml);

        Assert.NotNull(reloaded);
        Assert.True(reloaded.Strict);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "examples": [
    {
      "key": "value"
    }
  ],
  "strict": true,
  "properties": {
    "firstName": {
      "kind": "string",
      "sample": "Jane"
    },
    "lastName": {
      "kind": "string",
      "sample": "Doe"
    },
    "question": {
      "kind": "string",
      "sample": "What is the meaning of life?"
    }
  }
}
""";

        var instance = PropertySchema.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = PropertySchema.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
examples:
  - key: value
strict: true
properties:
  firstName:
    kind: string
    sample: Jane
  lastName:
    kind: string
    sample: Doe
  question:
    kind: string
    sample: What is the meaning of life?

""";

        var instance = PropertySchema.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = PropertySchema.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void LoadFromDictionary()
    {
        var data = new Dictionary<string, object?>();
        var instance = PropertySchema.Load(data);
        Assert.NotNull(instance);
    }

    [Fact]
    public void SaveToDictionary()
    {
        var instance = new PropertySchema();
        var data = instance.Save();
        Assert.NotNull(data);
        Assert.IsType<Dictionary<string, object?>>(data);
    }

}