
// Copyright (c) Microsoft. All rights reserved.
// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

using Xunit;

#pragma warning disable IDE0130
namespace AgentSchema;
#pragma warning restore IDE0130


public class ProtocolVersionRecordTests
{   
    [Fact]
    public void LoadYamlInput()
    {
        string yamlData = """
protocol: responses
version: v0.1.1

""";

        var instance = ProtocolVersionRecord.FromYaml(yamlData);

        Assert.NotNull(instance);
        Assert.Equal("responses", instance.Protocol);
        Assert.Equal("v0.1.1", instance.Version);
    }

    [Fact]
    public void LoadJsonInput()
    {
        string jsonData = """
{
  "protocol": "responses",
  "version": "v0.1.1"
}
""";

        var instance = ProtocolVersionRecord.FromJson(jsonData);
        Assert.NotNull(instance);
        Assert.Equal("responses", instance.Protocol);
        Assert.Equal("v0.1.1", instance.Version);
    }

    [Fact]
    public void RoundTripJson()
    {
        string jsonData = """
{
  "protocol": "responses",
  "version": "v0.1.1"
}
""";

        var instance = ProtocolVersionRecord.FromJson(jsonData);
        var json = instance.ToJson();
        var reloaded = ProtocolVersionRecord.FromJson(json);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Protocol, reloaded.Protocol);
        Assert.Equal(instance.Version, reloaded.Version);
    }

    [Fact]
    public void RoundTripYaml()
    {
        string yamlData = """
protocol: responses
version: v0.1.1

""";

        var instance = ProtocolVersionRecord.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        var reloaded = ProtocolVersionRecord.FromYaml(yaml);

        Assert.NotNull(reloaded);
        Assert.Equal(instance.Protocol, reloaded.Protocol);
        Assert.Equal(instance.Version, reloaded.Version);
    }

    [Fact]
    public void ToJsonOutput()
    {
        string jsonData = """
{
  "protocol": "responses",
  "version": "v0.1.1"
}
""";

        var instance = ProtocolVersionRecord.FromJson(jsonData);
        var json = instance.ToJson();
        
        Assert.NotNull(json);
        Assert.NotEmpty(json);
        // Verify output is valid JSON by parsing it
        var reloaded = ProtocolVersionRecord.FromJson(json);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void ToYamlOutput()
    {
        string yamlData = """
protocol: responses
version: v0.1.1

""";

        var instance = ProtocolVersionRecord.FromYaml(yamlData);
        var yaml = instance.ToYaml();
        
        Assert.NotNull(yaml);
        Assert.NotEmpty(yaml);
        // Verify output is valid YAML by parsing it
        var reloaded = ProtocolVersionRecord.FromYaml(yaml);
        Assert.NotNull(reloaded);
    }

    [Fact]
    public void LoadFromDictionary()
    {
        var data = new Dictionary<string, object?>();
        var instance = ProtocolVersionRecord.Load(data);
        Assert.NotNull(instance);
    }

    [Fact]
    public void SaveToDictionary()
    {
        var instance = new ProtocolVersionRecord();
        var data = instance.Save();
        Assert.NotNull(data);
        Assert.IsType<Dictionary<string, object?>>(data);
    }

}