##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import Any, ClassVar, Optional

from ._context import LoadContext, SaveContext


@dataclass
class ToolboxTool:
    """Represents a tool definition within a toolbox.
    Tools can be Foundry-hosted (bing_grounding, azure_ai_search, etc.)
    or external (mcp, openapi) with connection details.

    Attributes
    ----------
    id : str
        The tool type identifier (e.g., 'bing_grounding', 'azure_ai_search', 'mcp')
    name : Optional[str]
        Optional display name for the tool
    target : Optional[str]
        Target endpoint URL for external tools (e.g., MCP server URL)
    authType : Optional[str]
        Authentication type for the tool connection
    options : Optional[dict[str, Any]]
        Additional configuration options for the tool
    """

    _shorthand_property: ClassVar[Optional[str]] = None

    id: str = field(default="")
    name: Optional[str] = None
    target: Optional[str] = None
    authType: Optional[str] = None
    options: Optional[dict[str, Any]] = None

    @staticmethod
    def load(data: Any, context: Optional[LoadContext] = None) -> "ToolboxTool":
        """Load a ToolboxTool instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            ToolboxTool: The loaded ToolboxTool instance.

        """

        if context is not None:
            data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ToolboxTool: {data}")

        # create new instance
        instance = ToolboxTool()

        if data is not None and "id" in data:
            instance.id = data["id"]
        if data is not None and "name" in data:
            instance.name = data["name"]
        if data is not None and "target" in data:
            instance.target = data["target"]
        if data is not None and "authType" in data:
            instance.authType = data["authType"]
        if data is not None and "options" in data:
            instance.options = data["options"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: Optional[SaveContext] = None) -> dict[str, Any]:
        """Save the ToolboxTool instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        result: dict[str, Any] = {}

        if obj.id is not None:
            result["id"] = obj.id
        if obj.name is not None:
            result["name"] = obj.name
        if obj.target is not None:
            result["target"] = obj.target
        if obj.authType is not None:
            result["authType"] = obj.authType
        if obj.options is not None:
            result["options"] = obj.options

        if context is not None:
            result = context.process_dict(result)
        return result

    def to_yaml(self, context: Optional[SaveContext] = None) -> str:
        """Convert the ToolboxTool instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: Optional[SaveContext] = None, indent: int = 2) -> str:
        """Convert the ToolboxTool instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)
