# Copyright (c) Microsoft. All rights reserved.
# WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import json
import yaml

from agentschema import ObjectProperty


def test_load_json_objectproperty():
    json_data = """
    {
      "properties": {
        "property1": {
          "kind": "string"
        },
        "property2": {
          "kind": "number"
        }
      }
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ObjectProperty.load(data)
    assert instance is not None


def test_load_yaml_objectproperty():
    yaml_data = """
    properties:
      property1:
        kind: string
      property2:
        kind: number
    
    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = ObjectProperty.load(data)
    assert instance is not None


def test_roundtrip_json_objectproperty():
    """Test that load -> save -> load produces equivalent data."""
    json_data = """
    {
      "properties": {
        "property1": {
          "kind": "string"
        },
        "property2": {
          "kind": "number"
        }
      }
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = ObjectProperty.load(original_data)
    saved_data = instance.save()
    reloaded = ObjectProperty.load(saved_data)
    assert reloaded is not None


def test_roundtrip_yaml_objectproperty():
    """Test that YAML load -> save -> load produces equivalent data."""
    yaml_data = """
    properties:
      property1:
        kind: string
      property2:
        kind: number
    
    """
    original_data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = ObjectProperty.load(original_data)
    saved_data = instance.save()
    reloaded = ObjectProperty.load(saved_data)
    assert reloaded is not None


def test_to_json_objectproperty():
    """Test that to_json produces valid JSON."""
    json_data = """
    {
      "properties": {
        "property1": {
          "kind": "string"
        },
        "property2": {
          "kind": "number"
        }
      }
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ObjectProperty.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_objectproperty():
    """Test that to_yaml produces valid YAML."""
    json_data = """
    {
      "properties": {
        "property1": {
          "kind": "string"
        },
        "property2": {
          "kind": "number"
        }
      }
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ObjectProperty.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)


def test_load_objectproperty_from_dict():
    """Test loading from an empty dictionary."""
    data = {}
    instance = ObjectProperty.load(data)
    assert instance is not None


def test_save_objectproperty_to_dict():
    """Test saving to a dictionary."""
    instance = ObjectProperty()
    data = instance.save()
    assert data is not None
    assert isinstance(data, dict)
