# Copyright (c) Microsoft. All rights reserved.
# WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.

import json
import yaml

from agentschema import McpServerToolSpecifyApprovalMode


def test_load_json_mcpservertoolspecifyapprovalmode():
    json_data = """
    {
      "kind": "specify",
      "alwaysRequireApprovalTools": [
        "operation1"
      ],
      "neverRequireApprovalTools": [
        "operation2"
      ]
    }
    """
    data = json.loads(json_data, strict=False)
    instance = McpServerToolSpecifyApprovalMode.load(data)
    assert instance is not None
    assert instance.kind == "specify"


def test_load_yaml_mcpservertoolspecifyapprovalmode():
    yaml_data = """
    kind: specify
    alwaysRequireApprovalTools:
      - operation1
    neverRequireApprovalTools:
      - operation2
    
    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = McpServerToolSpecifyApprovalMode.load(data)
    assert instance is not None
    assert instance.kind == "specify"


def test_roundtrip_json_mcpservertoolspecifyapprovalmode():
    """Test that load -> save -> load produces equivalent data."""
    json_data = """
    {
      "kind": "specify",
      "alwaysRequireApprovalTools": [
        "operation1"
      ],
      "neverRequireApprovalTools": [
        "operation2"
      ]
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = McpServerToolSpecifyApprovalMode.load(original_data)
    saved_data = instance.save()
    reloaded = McpServerToolSpecifyApprovalMode.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "specify"


def test_roundtrip_yaml_mcpservertoolspecifyapprovalmode():
    """Test that YAML load -> save -> load produces equivalent data."""
    yaml_data = """
    kind: specify
    alwaysRequireApprovalTools:
      - operation1
    neverRequireApprovalTools:
      - operation2
    
    """
    original_data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = McpServerToolSpecifyApprovalMode.load(original_data)
    saved_data = instance.save()
    reloaded = McpServerToolSpecifyApprovalMode.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "specify"


def test_to_json_mcpservertoolspecifyapprovalmode():
    """Test that to_json produces valid JSON."""
    json_data = """
    {
      "kind": "specify",
      "alwaysRequireApprovalTools": [
        "operation1"
      ],
      "neverRequireApprovalTools": [
        "operation2"
      ]
    }
    """
    data = json.loads(json_data, strict=False)
    instance = McpServerToolSpecifyApprovalMode.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_mcpservertoolspecifyapprovalmode():
    """Test that to_yaml produces valid YAML."""
    json_data = """
    {
      "kind": "specify",
      "alwaysRequireApprovalTools": [
        "operation1"
      ],
      "neverRequireApprovalTools": [
        "operation2"
      ]
    }
    """
    data = json.loads(json_data, strict=False)
    instance = McpServerToolSpecifyApprovalMode.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)


def test_load_mcpservertoolspecifyapprovalmode_from_dict():
    """Test loading from an empty dictionary."""
    data = {}
    instance = McpServerToolSpecifyApprovalMode.load(data)
    assert instance is not None


def test_save_mcpservertoolspecifyapprovalmode_to_dict():
    """Test saving to a dictionary."""
    instance = McpServerToolSpecifyApprovalMode()
    data = instance.save()
    assert data is not None
    assert isinstance(data, dict)
